/* CONTENIDO DEL CURSO A1 · OFICINA — generado desde el legacy
   (public/js/a1-office-content.js, window.A1_OFFICE) y tipado contra el
   contrato compartido de '@/content/a1/tipos'.

   Los TEXTOS son VERBATIM: son la voz de Alfred, ya aprobada. Si hay que
   cambiar una tilde, se cambia acá y en ningún otro lado — la UI no reescribe
   nada del contenido, solo lo pinta.

   Los ids de chunk son la LLAVE del SRS (rodeo_a1_srs) y de las tareas
   (answerChunkId): renombrar uno le borra el progreso a quien ya lo tenía.
   7 unidades · 19 escenas · 63 chunks. */

import type { A1Course } from '@/content/a1/tipos';

export const A1_CURSO: A1Course = {
  version: 1,
  companion: {
    id: "alfred",
    name: "Alfred",
    fullName: "Alfredo",
    avatarInitial: "A",
    cardTheme: "peach",
    origin_es: "Paisa, de Medellín. Lleva un año en la empresa; ya se sabe el terreno.",
    tagline_es: "Tu colega en la oficina nueva.",
    intro_es: [
      "¡Ey! Vos sos el nuevo, ¿cierto? Yo soy Alfred, llevo un año acá.",
      "Tranquilo que yo te acompaño esta semana. A mí nadie me dijo nada y la sufrí.",
      "Acá no hay examen ni nadie te oye. Te equivocás las veces que querás. Ese es el punto.",
      "No vas a aprender inglés de libro. Vas a aprender lo que se dice el lunes a las 8.",
    ],
  },
  cognates: [
    { en: "information", es: "información", falseHook_es: null },
    { en: "professional", es: "profesional", falseHook_es: null },
    { en: "project", es: "proyecto", falseHook_es: null },
    { en: "client", es: "cliente", falseHook_es: null },
    { en: "office", es: "oficina", falseHook_es: null },
    { en: "experience", es: "experiencia", falseHook_es: null },
    { en: "company", es: "compañía", falseHook_es: null },
    { en: "communication", es: "comunicación", falseHook_es: null },
    { en: "presentation", es: "presentación", falseHook_es: null },
    { en: "position", es: "posición", falseHook_es: null },
    { en: "department", es: "departamento", falseHook_es: null },
    { en: "opportunity", es: "oportunidad", falseHook_es: null },
    { en: "important", es: "importante", falseHook_es: null },
    { en: "minute", es: "minuto", falseHook_es: null },
    { en: "problem", es: "problema", falseHook_es: null },
    {
      en: "meeting",
      es: "reunión",
      falseHook_es: "te suena a \"mitin\", úsalo de gancho pa' acordarte — pero ojo, un meeting es una reunión de trabajo, no un mitin político.",
    },
  ],
  units: [
    {
      id: "u1-llegar",
      order: 1,
      title_es: "Tu primer día: llegar y saludar",
      subtitle_es: "Entrar sin quedar mudo.",
      arc_es: "Llegas asustado. Alfred te adopta.",
      emoji: "😰",
      cardTheme: "blue",
      icon: "🚶",
      survival: false,
      companionSetup_es: [
        "Bueno, primer día. Respirá. Hoy solo hay que sobrevivir la llegada.",
        "Te enseño el saludo, cómo decir que sos nuevo, y cómo despedirte.",
      ],
      scenes: [
        {
          id: "u1-s1-pasillo",
          order: 1,
          title_es: "El saludo del pasillo",
          scene_es: "Te cruzás con tu jefe en el pasillo. Toca saludar.",
          icon: "🌅",
          setup_es: [
            "Ojo, ahí viene el jefe por el pasillo. En español le dirías \"buenas, ¿cómo va?\".",
            "En inglés hay una fórmula, toda junta. Te la muestro.",
          ],
          analogy_es: "Pensá en el saludo como abrir la puerta: primero saludás y ahí sí entrás al tema. Nadie negocia sin saludar.",
          chunks: [
            {
              id: "c-good-morning",
              en: "Good morning.",
              es: "Buenos días.",
              sounds_es: "gud mórnin",
              why_es: "El saludo base, el más seguro de todos. Con eso nunca quedás mal, se lo tirás a cualquiera.",
              sayWhen_es: "Al llegar en la mañana, con cualquiera.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Good night.", "Good luck."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-goodmorning-everyone",
              en: "Good morning, everyone.",
              es: "Buenos días a todos.",
              sounds_es: "gud mórnin, évriwan",
              why_es: "\"everyone\" es tu \"a todos\" sin nombrar a nadie uno por uno. Lo soltás al entrar y quedaste bien con toda la sala.",
              sayWhen_es: "Al entrar a una sala o al equipo.",
              who_es: "con cualquiera (seguro)",
              frame: "Good morning, ___.",
              swaps: ["everyone", "Sarah", "team"],
              distractors_es: ["Good night, everyone.", "See you, everyone."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-hows-it-going",
              en: "Hi, how's it going?",
              es: "Hola, ¿cómo va?",
              sounds_es: "jái, jáus it góin",
              why_es: "Es el \"¿bien o qué?\" gringo. No esperan tu biografía: se contesta \"good, you?\" y ya. Con el parcero del cubículo, no con el CEO en el ascensor.",
              sayWhen_es: "Saludo casual, de pasada, con un compa.",
              who_es: "con el parcero",
              frame: null,
              swaps: null,
              distractors_es: ["Hi, where is it?", "Hi, how much is it?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
        {
          id: "u1-s2-conocer",
          order: 2,
          title_es: "Conocer a alguien",
          scene_es: "Alguien del equipo se te acerca a conocerte.",
          icon: "🤝",
          setup_es: [
            "Se te arrima un compañero a saludar. Con dos frasecitas quedás como gente.",
            "Una pa' el saludo de mano, otra pa' preguntarle el nombre.",
          ],
          analogy_es: "Conocer a alguien es como el saludo de mano: se hace una sola vez, el primer día, y ahí arranca la relación.",
          chunks: [
            {
              id: "c-nice-to-meet-you",
              en: "Nice to meet you.",
              es: "Mucho gusto.",
              sounds_es: "náis tu mít iú",
              why_es: "El apretón de manos hecho frase. Se dice UNA vez, el día que conocés a alguien. Como estrenar zapatos: solo el primer día.",
              sayWhen_es: "El día que conocés a alguien, una sola vez.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Nice to see you again.", "Meet you nice."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-whats-your-name",
              en: "What's your name?",
              es: "¿Cómo te llamas?",
              sounds_es: "guáts iór néim",
              why_es: "La llave pa' conocer a cualquiera. Cortica y educada; con eso arrancás toda presentación.",
              sayWhen_es: "Cuando querés saber cómo se llama alguien.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["What is your work?", "Where's your name?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
        {
          id: "u1-s3-presentarte",
          order: 3,
          title_es: "Decir quién sos y despedirte",
          scene_es: "Te presentan y, al rato, se acaba el día.",
          icon: "🪪",
          setup_es: [
            "Primero tu escudo de nuevo, que nadie te va a exigir de más.",
            "Y al final, el chao del día, suavecito.",
          ],
          analogy_es: "Decir que sos nuevo no es debilidad: es un escudo. El que avisa que va llegando recibe ayuda en vez de exigencia.",
          chunks: [
            {
              id: "c-im-new-here",
              en: "I'm new here.",
              es: "Soy nuevo aquí.",
              sounds_es: "áim niú jíar",
              why_es: "Tu carné de recién llegado. Bájale a las expectativas y todo el mundo te ayuda. Es una frase-escudo, no una vergüenza.",
              sayWhen_es: "Cuando querés que te tengan paciencia.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["I'm fine here.", "I'm not here."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-have-a-good-day",
              en: "Have a good day.",
              es: "Que tengas buen día.",
              sounds_es: "jav a gud déi",
              why_es: "El cierre amable de salida. Se regala fácil y cae bien; no cuesta nada y te deja bien parado.",
              sayWhen_es: "Al despedirte, saliendo.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Have a good name.", "Give a good day."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-see-you-tomorrow",
              en: "See you tomorrow.",
              es: "Nos vemos mañana.",
              sounds_es: "síi iú tumórou",
              why_es: "\"See you\" + cuándo: tomorrow, on Monday, later. El chao de oficina; cambiás la colita y ya.",
              sayWhen_es: "Al salir, si mañana volvés a ver a la persona.",
              who_es: "con cualquiera (seguro)",
              frame: "See you ___.",
              swaps: ["tomorrow", "on Monday", "later"],
              distractors_es: ["See you never.", "I see you tomorrow morning early."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
      ],
      task: {
        id: "u1-task",
        intro_es: "Listo. Ahora sobreviví tu primera mañana. Vas entrando…",
        steps: [
          {
            goal_es: "Te cruzás al de recepción y a medio equipo. Salúdalos a todos de una.",
            answerChunkId: "c-goodmorning-everyone",
            reaction_es: "¡Eso! Entraste como si nada.",
          },
          {
            goal_es: "Te presentan a tu jefa. Decile que sos nuevo.",
            answerChunkId: "c-im-new-here",
            reaction_es: "Perfecto, con eso bajás expectativas y te ayudan.",
          },
          {
            goal_es: "Se acaba el día. Despedite pa' mañana.",
            answerChunkId: "c-see-you-tomorrow",
            reaction_es: "Sobreviviste el día 1, parce. En serio.",
          },
        ],
        done_es: "Ya sabés LLEGAR A LA OFICINA. ✓",
      },
    },
    {
      id: "u2-supervivencia",
      order: 2,
      title_es: "Tu kit de supervivencia",
      subtitle_es: "Las que te salvan de cualquier lío.",
      arc_es: "Ya no entendés algo. En vez de asentir y hacer la tarea mala, aprendés a pedir.",
      emoji: "🪂",
      cardTheme: "yellow",
      icon: "🛟",
      survival: true,
      companionSetup_es: [
        "Estas son las que te salvan de cualquier lío. Apréndetelas primero y ya nada te asusta.",
        "Con estas cinco, aunque no entendás nada, no te ahogás. Son tu red.",
      ],
      scenes: [
        {
          id: "u2-s1-no-entendiste",
          order: 1,
          title_es: "No entendiste",
          scene_es: "Te hablan en inglés y se te fue el hilo. Pasa.",
          icon: "🙉",
          setup_es: [
            "Te hablaron y no cazaste nada. Fresco, a todos nos pasa.",
            "Nadie se enoja si pedís que repitan: prefieren repetírtelo a que hagás algo mal.",
          ],
          analogy_es: "Pedir que repitan es de vivos, no de bobos. Es el botón de rebobinar: lo apretás sin pena y listo.",
          chunks: [
            {
              id: "c-dont-understand",
              en: "Sorry, I don't understand.",
              es: "Perdón, no entiendo.",
              sounds_es: "sóri, ái dont anderstánd",
              why_es: "Decir esto es de vivos, no de bobos. Nadie se enoja: prefieren repetirte a que hagás algo mal.",
              sayWhen_es: "Cuando no entendiste y toca decirlo.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Sorry, I don't listen.", "Sorry, I understand nothing here."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: true,
            },
            {
              id: "c-repeat",
              en: "Can you repeat that, please?",
              es: "¿Puedes repetir eso, por favor?",
              sounds_es: "kan iú ripít dat, plís",
              why_es: "El botón de rebobinar hablado. El \"please\" al final es el aceitico pa' que no suene grosero.",
              sayWhen_es: "Cuando necesitás que repitan algo.",
              who_es: "con cualquiera (seguro)",
              frame: "Can you ___, please?",
              swaps: ["repeat that", "speak slowly", "help me"],
              distractors_es: ["Can you repeat that, thanks?", "You repeat that now."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: true,
            },
            {
              id: "c-speak-slowly",
              en: "Can you speak slowly, please?",
              es: "¿Puedes hablar despacio, por favor?",
              sounds_es: "kan iú spík slóuli, plís",
              why_es: "Nadie se ofende si pedís despacio. Al contrario: prefieren repetírtelo a que hagás algo mal.",
              sayWhen_es: "Cuando hablan muy rápido.",
              who_es: "con cualquiera (seguro)",
              frame: "Can you ___, please?",
              swaps: ["speak slowly", "repeat that", "help me"],
              distractors_es: ["Can you speak slow, please?", "Speak slowly you, please?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: true,
            },
            {
              id: "c-didnt-catch",
              en: "Sorry, I didn't catch that.",
              es: "Perdón, no alcancé a oír.",
              sounds_es: "sóri, ái dídnt kach dat",
              why_es: "\"catch\" es atrapar: no atrapaste la pelota de lo que dijeron. Suena mejor que \"I don't understand\" porque no admite que fallaste vos.",
              sayWhen_es: "Cuando no alcanzaste a oír bien.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Sorry, I didn't hear you good.", "Sorry, I don't catch."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: true,
            },
          ],
        },
        {
          id: "u2-s2-falta-palabra",
          order: 2,
          title_es: "Te falta una palabra",
          scene_es: "Cae una palabra que no conocés y te trabás.",
          icon: "🗺️",
          setup_es: [
            "Cuando te falta una palabra, preguntás en vez de congelarte.",
            "Y si necesitás una pausita o una mano, también se pide sin drama.",
          ],
          analogy_es: "Preguntar qué significa algo es como pedir el mapa cuando estás perdido: no es rendirse, es lo que hace el que sabe moverse.",
          chunks: [
            {
              id: "c-what-does-that-mean",
              en: "What does that mean?",
              es: "¿Qué significa eso?",
              sounds_es: "guát das dat mín",
              why_es: "Tu comodín cuando cae una palabra que no conocés. Preguntar es de vivos, no de bobos.",
              sayWhen_es: "Cuando cae una palabra que no conocés.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["What does that means?", "What that mean does?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-how-do-you-say",
              en: "How do you say this in English?",
              es: "¿Cómo se dice esto en inglés?",
              sounds_es: "jáu du iú séi dis in ínglish",
              why_es: "Cuando te falta la palabra, preguntás en vez de congelarte. Es de vivos, no de bobos.",
              sayWhen_es: "Cuando te falta la palabra en inglés.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["How you say this in English?", "How do you say this on English?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-help-me-with-this",
              en: "Can you help me with this?",
              es: "¿Me ayudas con esto?",
              sounds_es: "kan iú jelp mi güid dis",
              why_es: "\"help me WITH algo\": el \"with\" es la mano que señala QUÉ. Pedís ayuda apuntando al problema.",
              sayWhen_es: "Cuando necesitás una mano con algo.",
              who_es: "con cualquiera (seguro)",
              frame: "Can you help me with ___?",
              swaps: ["this", "the report", "the printer"],
              distractors_es: ["Can you help me on this?", "Can you help this with me?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: true,
            },
            {
              id: "c-one-moment",
              en: "One moment, please.",
              es: "Un momento, por favor.",
              sounds_es: "guán móument, plís",
              why_es: "Pa' pedir una pausita sin enredarte. Ganás dos segundos y no te ahogás.",
              sayWhen_es: "Cuando necesitás una pausita.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["One minute, thanks.", "A moment, one please."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
      ],
      task: {
        id: "u2-task",
        intro_es: "Bueno, ahora imaginate en una reunión y no entendés nada. Sacá tus salvavidas…",
        steps: [
          {
            goal_es: "El jefe dijo algo rapidísimo. Pedile que lo repita.",
            answerChunkId: "c-repeat",
            reaction_es: "¡Eso! Y nadie se enojó, ¿viste?",
          },
          {
            goal_es: "Habla como una metralleta. Pedile que hable despacio.",
            answerChunkId: "c-speak-slowly",
            reaction_es: "De una. Ahí ya lo agarrás todo.",
          },
          {
            goal_es: "Cayó una palabra rara. Preguntá qué significa.",
            answerChunkId: "c-what-does-that-mean",
            reaction_es: "Perfecto. Preguntar es de vivos, parce.",
          },
        ],
        done_es: "Ya tenés tu KIT DE SUPERVIVENCIA. ✓ Con esas no te ahogás.",
      },
    },
    {
      id: "u3-presentarte",
      order: 3,
      title_es: "Preséntate y conocé al equipo",
      subtitle_es: "Decir quién sos sin trabarte.",
      arc_es: "Ya no estás tan asustado. Te presentás y empezás a pertenecer.",
      emoji: "👋",
      cardTheme: "lavender",
      icon: "👥",
      survival: false,
      companionSetup_es: [
        "Hoy te presento con el equipo. Suena feo, pero con dos o tres frases quedás.",
        "Aprendés a decir qué hacés, de dónde sos, y a devolver la pregunta pa' que no se muera la charla.",
      ],
      scenes: [
        {
          id: "u3-s1-equipo",
          order: 1,
          title_es: "Te presentan al equipo",
          scene_es: "Alfred te lleva donde el equipo. Te van a saludar uno por uno.",
          icon: "🤝",
          setup_es: [
            "Te van a presentar con el equipo, uno por uno. Tranquilo, es rapidito.",
            "Con devolver el saludo y hacer una preguntica, ya quedás como gente.",
          ],
          analogy_es: "Conocer al equipo es como llegar a un asado ajeno: saludás, preguntás algo y ya dejás de ser el desconocido del rincón.",
          chunks: [
            {
              id: "c-nice-to-meet-you-too",
              en: "Nice to meet you too.",
              es: "Igualmente, mucho gusto.",
              sounds_es: "náis tu mít iú tú",
              why_es: "Cuando te dicen \"nice to meet you\", vos rebotás lo mismo con un \"too\" pegado al final. Es el \"igualmente\" de toda la vida: la pelota que te tiran, la devolvés.",
              sayWhen_es: "Cuando te dicen \"nice to meet you\" y respondés.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Nice to see you too.", "Good to meet you first."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-what-do-you-do",
              en: "What do you do here?",
              es: "¿Qué hacés aquí?",
              sounds_es: "guát du iú du jíar",
              why_es: "Es el \"¿y vos en qué andás?\" de oficina. Rompe el hielo sin meterte en la vida de nadie: preguntás por el trabajo, no por el chisme.",
              sayWhen_es: "Pa' preguntarle a alguien en qué trabaja.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["What do you have here?", "Where do you go here?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-where-do-you-work",
              en: "Where do you work?",
              es: "¿Dónde trabajás?",
              sounds_es: "güér du iú guórk",
              why_es: "Devolvés la pregunta pa' que la charla no se muera. El small talk es como el ping-pong: si no la devolvés, se cae la bolita y quedás de mudo.",
              sayWhen_es: "Pa' devolver la pregunta y seguir la charla.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Where do you live?", "When do you work?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-how-long-worked",
              en: "How long have you worked here?",
              es: "¿Cuánto llevás trabajando aquí?",
              sounds_es: "jáu long jav iú guórkt jíar",
              why_es: "Con esta mostrás interés sin ser metido. A la gente le encanta contar su propia historia: le abrís la puerta y solita se pone a hablar.",
              sayWhen_es: "Cuando querés mostrar interés en la otra persona.",
              who_es: "con el parcero",
              frame: null,
              swaps: null,
              distractors_es: ["How long is the work?", "How many work here?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
        {
          id: "u3-s2-quien-sos",
          order: 2,
          title_es: "Qué hacés y de dónde sos",
          scene_es: "Te preguntan en qué trabajás y de dónde venís.",
          icon: "🌎",
          setup_es: [
            "Ahora te toca hablar un poquito de vos: tu equipo, tu país.",
            "Son moldes: le metés tu área o tu país y listo, no hay que inventar nada.",
          ],
          analogy_es: "Contar qué hacés es como ponerte el uniforme del equipo: con una frase la gente ya sabe dónde encajás y en qué te pueden buscar.",
          chunks: [
            {
              id: "c-work-in-sales",
              en: "I work in the sales team.",
              es: "Trabajo en el equipo de ventas.",
              sounds_es: "ái guórk in de séils tim",
              why_es: "Es tu molde pa' decir de qué equipo sos: le metés tu área y listo. Como el letrerito del escritorio que dice dónde encajás.",
              sayWhen_es: "Cuando te preguntan a qué te dedicás.",
              who_es: "con cualquiera (seguro)",
              frame: "I work in ___.",
              swaps: ["the sales team", "sales", "support"],
              distractors_es: ["I like the sales team.", "I have a sales meeting."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-on-design-team",
              en: "I'm on the design team.",
              es: "Estoy en el equipo de diseño.",
              sounds_es: "áim on de disáin tim",
              why_es: "\"on the ___ team\" es como decir \"soy de la selección de…\". No es que trabajés cerca del equipo: es que sos del equipo, jugás ahí.",
              sayWhen_es: "Cuando decís de qué equipo sos.",
              who_es: "con cualquiera (seguro)",
              frame: "I'm on the ___ team.",
              swaps: ["design", "sales", "support"],
              distractors_es: ["I like the design team.", "I want the design team."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-im-from-colombia",
              en: "I'm from Colombia.",
              es: "Soy de Colombia.",
              sounds_es: "áim from colómbia",
              why_es: "Tu molde pa' decir de dónde venís: cambiás el país y ya. Es la banderita que te ponés en el pecho sin tener que explicar más.",
              sayWhen_es: "Cuando te preguntan de dónde sos.",
              who_es: "con cualquiera (seguro)",
              frame: "I'm from ___.",
              swaps: ["Colombia", "Mexico", "Peru"],
              distractors_es: ["I live in Colombia.", "I go to Colombia."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-my-first-week",
              en: "This is my first week.",
              es: "Esta es mi primera semana.",
              sounds_es: "dis is mái ferst güík",
              why_es: "Es el escudo de nuevo, versión semana: avisás que vas llegando y la gente te da tiempo y paciencia en vez de exigirte de una.",
              sayWhen_es: "Cuando querés que te tengan paciencia de nuevo.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["This is my first day.", "This is my last week."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
      ],
      task: {
        id: "u3-task",
        intro_es: "Bueno, te toca presentarte con el equipo. Sin miedo, que ya tenés con qué…",
        steps: [
          {
            goal_es: "Te presentan a una compañera. Devolvele el saludo.",
            answerChunkId: "c-nice-to-meet-you-too",
            reaction_es: "¡Eso! Con el \"too\" quedaste como gente.",
          },
          {
            goal_es: "Te preguntan en qué andás. Decí que trabajás en ventas.",
            answerChunkId: "c-work-in-sales",
            reaction_es: "De una. Ya saben de qué equipo sos.",
          },
          {
            goal_es: "Querés saber de la otra persona. Preguntale dónde trabaja.",
            answerChunkId: "c-where-do-you-work",
            reaction_es: "Eso, devolviste la pregunta. Así no se muere la charla.",
          },
        ],
        done_es: "Ya sabés PRESENTARTE Y CONOCER AL EQUIPO. ✓",
      },
    },
    {
      id: "u4-smalltalk",
      order: 4,
      title_es: "Small talk y cortesía",
      subtitle_es: "La charlita que te hace del parche.",
      arc_es: "Descubrís que la charla boba del café es la que te mete en el grupo.",
      emoji: "☕",
      cardTheme: "green",
      icon: "💬",
      survival: false,
      companionSetup_es: [
        "Bienvenido al small talk: esa charlita boba del cafecito que acá no es opcional.",
        "Es el aceitico social. Con estas frasecitas dejás de ser el mudo del rincón.",
      ],
      scenes: [
        {
          id: "u4-s1-lunes",
          order: 1,
          title_es: "El lunes en la mañana",
          scene_es: "Lunes, 8 a.m. Todos con el cafecito preguntando por el finde.",
          icon: "☀️",
          setup_es: [
            "Es lunes y arranca el ritual del cafecito: \"¿cómo te fue el finde?\".",
            "No es chisme, es el saludo largo. El que no lo hace queda de raro.",
          ],
          analogy_es: "El small talk del lunes es como calentar el carro antes de arrancar: dos minuticos de charla boba y ya la relación anda suave todo el día.",
          chunks: [
            {
              id: "c-how-was-weekend",
              en: "How was your weekend?",
              es: "¿Cómo estuvo tu finde?",
              sounds_es: "jáu guas iór güíkend",
              why_es: "El clásico del lunes. Acá el small talk no es opcional: es el aceitico que hace que la máquina de la oficina no chirríe. Preguntás y ya sos gente.",
              sayWhen_es: "El lunes, pa' preguntar por el fin de semana.",
              who_es: "con cualquiera (seguro)",
              frame: "How was your ___?",
              swaps: ["weekend", "trip", "call"],
              distractors_es: ["How is your work?", "How was your week?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-how-are-you-today",
              en: "How are you today?",
              es: "¿Cómo estás hoy?",
              sounds_es: "jáu ar iú tudéi",
              why_es: "Saludo seguro con quien sea. Ojo: no es interrogatorio de verdad — contestan \"good, thanks\" y vos igual. Es un apretón de manos con palabras, no una consulta médica.",
              sayWhen_es: "Saludo del día, con cualquiera.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["How old are you today?", "How was you today?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-excited-to-be-here",
              en: "I'm excited to be here.",
              es: "Me alegra estar aquí.",
              sounds_es: "áim eksáited tu bi jíar",
              why_es: "Se la tirás al jefe o al equipo el primer día y quedás como oro. Es la sonrisa hecha frase: dice que llegás con ganas, no muerto del susto.",
              sayWhen_es: "Tu primer día, con el jefe o el equipo.",
              who_es: "con el jefe",
              frame: null,
              swaps: null,
              distractors_es: ["I am tired to be here.", "I am excited for here."],
              cognateHook_es: "Ojo: \"excited\" no es \"excitado\" (esa en español es otra cosa). Acá es \"emocionado\", \"con ganas\".",
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
        {
          id: "u4-s2-cortesia",
          order: 2,
          title_es: "Gracias y de nada",
          scene_es: "Alguien te hace un favor. Toca agradecer y saber responder.",
          icon: "🙏",
          setup_es: [
            "Te van a hacer favores y a agradecerte. Hay que saber ir y volver.",
            "Un \"gracias\" fuerte y un \"de nada\" bien puesto: con eso quedás fino.",
          ],
          analogy_es: "Gracias y de nada son como el saludo de mano de ida y vuelta: uno estira, el otro responde. Si dejás al otro con la mano estirada, quedás mal.",
          chunks: [
            {
              id: "c-thanks-a-lot",
              en: "Thanks a lot.",
              es: "Muchas gracias.",
              sounds_es: "zanks a lot",
              why_es: "\"a lot\" es el sube-volumen del \"thanks\": mismo gracias, pero más fuerte. Como cuando le subís el brazo al saludo pa' que se note más.",
              sayWhen_es: "Cuando querés agradecer con ganas.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Thanks a little.", "Thank you lot."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-no-problem",
              en: "No problem.",
              es: "Con gusto / no hay lío.",
              sounds_es: "nou próblem",
              why_es: "Cuando te dan las gracias, esta es la que rebotás con el parcero. Es el \"fresco, no hay lío\" de toda la vida: le quitás peso al favor.",
              sayWhen_es: "Cuando te agradecen y respondés relajado.",
              who_es: "con el parcero",
              frame: null,
              swaps: null,
              distractors_es: ["No, thanks.", "Never mind."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-youre-welcome",
              en: "You're welcome.",
              es: "De nada.",
              sounds_es: "iúr güélcom",
              why_es: "El \"de nada\" neutro, el que le podés decir hasta al jefe sin pena. Cuando dudés entre este y \"no problem\", con este nunca te caés.",
              sayWhen_es: "Cuando te dan las gracias, versión neutra.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Welcome, you.", "You are new here."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-same-to-you",
              en: "Same to you.",
              es: "Igualmente.",
              sounds_es: "séim tu iú",
              why_es: "Cuando te desean algo bueno (\"have a good weekend\"), en vez de repetir todo el rollo, rebotás \"same to you\" y quedás fino. Es el espejo: te deseo lo mismo.",
              sayWhen_es: "Cuando te desean algo y lo devolvés.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Same for me too.", "Some to you."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-have-a-good-weekend",
              en: "Have a good weekend.",
              es: "Buen fin de semana.",
              sounds_es: "jav a gud güíkend",
              why_es: "La frase del viernes. El día que la soltás y te la devuelven sin pensar, ya sos del parche: esa es la señal de que te adoptaron.",
              sayWhen_es: "El viernes, al despedirte.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Have a good week.", "Have the good weekend."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
      ],
      task: {
        id: "u4-task",
        intro_es: "Es lunes, llegás y todos están con el cafecito. Toca romper el hielo…",
        steps: [
          {
            goal_es: "Te cruzás a un compañero un lunes. Preguntá cómo estuvo su finde.",
            answerChunkId: "c-how-was-weekend",
            reaction_es: "¡Eso! Con esa ya sos parte del cafecito.",
          },
          {
            goal_es: "Te hacen un favor. Dales las gracias fuerte.",
            answerChunkId: "c-thanks-a-lot",
            reaction_es: "De una. Un gracias así nunca sobra.",
          },
          {
            goal_es: "Es viernes, te vas. Deseá buen finde.",
            answerChunkId: "c-have-a-good-weekend",
            reaction_es: "Y si te lo devuelven… ya sos del parche, parce.",
          },
        ],
        done_es: "Ya sabés HACER SMALL TALK SIN SUDAR. ✓",
      },
    },
    {
      id: "u5-ayuda",
      order: 5,
      title_es: "Pedir ayuda y ubicarte",
      subtitle_es: "Moverte y pedir sin pena.",
      arc_es: "Ya te movés por la oficina como en tu casa. Pedir ayuda es de vivos.",
      emoji: "🧭",
      cardTheme: "paper",
      icon: "🙋",
      survival: false,
      companionSetup_es: [
        "Ahora toca moverte por la oficina y pedir cosas sin pena.",
        "Dónde queda el baño, cómo pedir una mano, cómo pedir que te manden algo. Puro sobrevivir.",
      ],
      scenes: [
        {
          id: "u5-s1-ubicarte",
          order: 1,
          title_es: "Ubicarte e instalarte",
          scene_es: "Primer día en tu puesto. Necesitás ubicar todo y marcar lo tuyo.",
          icon: "🚻",
          setup_es: [
            "Antes que nada, ubicá lo básico y marcá tu puesto. Es tu territorio.",
            "Y tranquilo: acá se puede preguntar. Pedir permiso no le molesta a nadie.",
          ],
          analogy_es: "Instalarte es como llegar a un salón de clase nuevo: ubicás el baño, agarrás tu puesto y ya dejás de andar perdido mirando pa' todo lado.",
          chunks: [
            {
              id: "c-where-is-bathroom",
              en: "Where is the bathroom?",
              es: "¿Dónde queda el baño?",
              sounds_es: "güér is de bázrum",
              why_es: "Supervivencia pura, la primera que vas a necesitar. \"Where is the ___?\" es tu brújula: le metés lo que buscás y te ubican.",
              sayWhen_es: "Cuando necesitás ubicar el baño (o lo que sea).",
              who_es: "con cualquiera (seguro)",
              frame: "Where is the ___?",
              swaps: ["bathroom", "printer", "kitchen", "exit"],
              distractors_es: ["Where is my bathroom?", "Where are the bathroom?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-this-is-my-desk",
              en: "This is my desk.",
              es: "Este es mi escritorio.",
              sounds_es: "dis is mái desk",
              why_es: "Chiquita pero tuya. \"This is my ___\" es el dedito que señala: my desk, my laptop, my badge. Marcás tu territorio sin pelear con nadie.",
              sayWhen_es: "Pa' señalar tu puesto o algo tuyo.",
              who_es: "con cualquiera (seguro)",
              frame: "This is my ___.",
              swaps: ["desk", "laptop", "badge"],
              distractors_es: ["This is your desk.", "That is a desk."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-can-i-ask",
              en: "Can I ask a question?",
              es: "¿Puedo hacer una pregunta?",
              sounds_es: "kan ái ask a kuéschon",
              why_es: "\"Can I…?\" es tu llave maestra: pedís permiso sin sonar mandón. Es como tocar la puerta antes de entrar — con eso nadie se molesta.",
              sayWhen_es: "Antes de soltar una pregunta, pa' pedir permiso.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Can I make a question?", "Can I ask the answer?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
        {
          id: "u5-s2-pedir",
          order: 2,
          title_es: "Pedir una mano",
          scene_es: "Te trabás con algo y necesitás que alguien te ayude.",
          icon: "🤲",
          setup_es: [
            "Te vas a trabar, es normal el primer día. Lo bueno es saber pedir.",
            "Una mano, un archivo, un minutico: todo se pide sin pena y con \"please\".",
          ],
          analogy_es: "Pedir ayuda es como pedir el paso en la fila: no es rendirse, es lo que hace el que sabe moverse. El que se queda callado es el que se enreda.",
          chunks: [
            {
              id: "c-can-you-help-me",
              en: "Can you help me, please?",
              es: "¿Me puedes ayudar, por favor?",
              sounds_es: "kan iú jelp mi, plís",
              why_es: "El pedido de ayuda pa' todo, con el \"please\" de aceitico. Pedir ayuda no es de brutos: el que pregunta llega, el que se queda callado se enreda.",
              sayWhen_es: "Cuando te trabás y necesitás una mano.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Can I help you, please?", "Can you see me, please?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-send-it-to-me",
              en: "Can you send it to me?",
              es: "¿Me lo puedes enviar?",
              sounds_es: "kan iú send it tu mi",
              why_es: "\"send it TO me\": el \"to\" es la flechita que dice pa' quién va la cosa. Sin esa flechita, el archivo no sabe a dónde llegar.",
              sayWhen_es: "Cuando querés que te manden un archivo.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Can you send it for me?", "Can you send me it to?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-do-you-have-a-minute",
              en: "Do you have a minute?",
              es: "¿Tienes un minuto?",
              sounds_es: "du iú jav a mínit",
              why_es: "Pedís un ratico sin robártelo. Preguntás primero si puede, en vez de caerle encima: por eso casi siempre te dicen que sí.",
              sayWhen_es: "Cuando necesitás un ratico de alguien.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Do you have the time?", "Have you a minute?"],
              cognateHook_es: "\"minute\" es \"minuto\", casi la misma palabra. Esa ya la tenías.",
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
        {
          id: "u5-s3-entender",
          order: 3,
          title_es: "Entender cómo funciona todo",
          scene_es: "Todo es nuevo: la impresora, el programa, hasta dónde sentarte.",
          icon: "🧩",
          setup_es: [
            "El primer día no sabés ni prender la impresora, y es normal. Nadie nace sabiendo.",
            "Estas cuatro son pa' preguntar sin pena: cómo se usa, que te muestren, dónde te ubicás y a quién le caés.",
          ],
          analogy_es: "Tu primer día es como estrenar celu nuevo: no sabés dónde queda nada. Preguntar no es de perdido — es lo que hace que en dos días ya te muevas solo.",
          chunks: [
            {
              id: "c-how-does-this-work",
              en: "How does this work?",
              es: "¿Cómo funciona esto?",
              sounds_es: "jáu das dis guórk",
              why_es: "La que sacás frente a la impresora rara o el programa que nadie te explicó. Preguntar cómo se usa algo el primer día es como pedir el manual: nadie espera que nazcas sabiendo.",
              sayWhen_es: "Cuando no sabés usar una máquina o un programa.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["How this works?", "How does this works?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-can-you-show-me",
              en: "Can you show me?",
              es: "¿Me puedes mostrar?",
              sounds_es: "kan iú shóu mi",
              why_es: "A veces con que te lo cuenten no basta. \"Show me\" es pedir que te lo hagan ver — como decir \"hacelo vos primero y yo miro\". Más claro que mil explicaciones.",
              sayWhen_es: "Cuando querés que te enseñen haciéndolo, no contándolo.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Can you show to me?", "Can you show me it?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-where-do-i-sit",
              en: "Where do I sit?",
              es: "¿Dónde me siento?",
              sounds_es: "güér du ái sit",
              why_es: "El primer día es como subirte a un bus lleno: no sabés cuál silla es tuya. \"Where do I ___?\" pregunta dónde te toca a vos, sin quedar parado como poste.",
              sayWhen_es: "Cuando no sabés cuál es tu lugar o puesto.",
              who_es: "con cualquiera (seguro)",
              frame: "Where do I ___?",
              swaps: ["sit", "go", "sign"],
              distractors_es: ["Where I sit?", "Where do I sit it?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-who-should-i-ask",
              en: "Who should I ask?",
              es: "¿A quién le pregunto?",
              sounds_es: "jú shud ái ask",
              why_es: "Cuando tenés una duda pero no sabés a quién caerle. En vez de tocar diez puertas, con esta preguntás cuál es la puerta correcta. Te ahorra vueltas.",
              sayWhen_es: "Cuando tenés una duda y no sabés quién la resuelve.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Who I should ask?", "Who should I ask to?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
        {
          id: "u5-s4-descanso",
          order: 4,
          title_es: "Permiso, la hora y el descanso",
          scene_es: "Llevás horas pegado a la silla. Necesitás un respiro y saber a qué hora es todo.",
          icon: "☕",
          setup_es: [
            "Nadie aguanta ocho horas sin parar. Pedir un descanso es normal y sano.",
            "Y pa' no andar perdido: aprendé a preguntar a qué hora es cada cosa.",
          ],
          analogy_es: "Pedir un respiro es como pedir agua en un partido: no es rendirse, es lo que te deja seguir jugando bien. Y preguntar la hora te ubica, como mirar el reloj del estadio.",
          chunks: [
            {
              id: "c-can-i-take-a-break",
              en: "Can I take a break?",
              es: "¿Puedo tomar un descanso?",
              sounds_es: "kan ái téik a bréik",
              why_es: "Pedir el descanso no es de flojo, es de vivo: rendís más si parás tantico. \"Can I…?\" pide permiso sin sonar mandón, como tocar la puerta antes de entrar.",
              sayWhen_es: "Cuando necesitás parar un rato pa' respirar.",
              who_es: "con el jefe",
              frame: null,
              swaps: null,
              distractors_es: ["Can I take break?", "Can I make a break?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-what-time-is-lunch",
              en: "What time is lunch?",
              es: "¿A qué hora es el almuerzo?",
              sounds_es: "guát táim is lonch",
              why_es: "Pa' ubicarte en el día sin andar perdido. \"What time is ___?\" es el molde pa' preguntar la hora de cualquier cosa: el almuerzo, la reunión, la llamada. Le metés lo que sea y ya.",
              sayWhen_es: "Cuando querés saber a qué hora es algo.",
              who_es: "con cualquiera (seguro)",
              frame: "What time is ___?",
              swaps: ["lunch", "the meeting", "the call"],
              distractors_es: ["What hour is lunch?", "What time lunch is?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-ill-be-right-back",
              en: "I'll be right back.",
              es: "Ya vuelvo.",
              sounds_es: "áil bi ráit bak",
              why_es: "La que soltás antes de pararte: avisás en vez de desaparecer, y nadie se queda esperando pensando que te fuiste. Cortica y educada.",
              sayWhen_es: "Antes de levantarte un momentico.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["I be right back.", "I'll be right come back."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
      ],
      task: {
        id: "u5-task",
        intro_es: "Primer día en tu puesto y necesitás moverte. A ver, pedí sin pena…",
        steps: [
          {
            goal_es: "Te estás aguantando las ganas. Preguntá dónde queda el baño.",
            answerChunkId: "c-where-is-bathroom",
            reaction_es: "¡Eso! Esa es la primera que salva a todo el mundo.",
          },
          {
            goal_es: "Te trabaste con algo. Pedí una mano.",
            answerChunkId: "c-can-you-help-me",
            reaction_es: "Perfecto. El que pregunta llega, ¿si me entendés?",
          },
          {
            goal_es: "Necesitás que te pasen un archivo. Pedí que te lo manden.",
            answerChunkId: "c-send-it-to-me",
            reaction_es: "De una. Con la flechita del \"to\" bien puesta.",
          },
          {
            goal_es: "La impresora no te obedece y nadie te explicó. Preguntá cómo funciona.",
            answerChunkId: "c-how-does-this-work",
            reaction_es: "¡Eso! Preguntar cómo se usa algo es de vivo, no de bruto.",
          },
          {
            goal_es: "Llevás horas sin parar. Pedile permiso al jefe pa' un descanso.",
            answerChunkId: "c-can-i-take-a-break",
            reaction_es: "Eso, parce. Un respiro a tiempo y volvés con toda.",
          },
        ],
        done_es: "Ya sabés PEDIR AYUDA Y UBICARTE. ✓",
      },
    },
    {
      id: "u6-reunion",
      order: 6,
      title_es: "En la reunión sin miedo",
      subtitle_es: "Entrar, opinar y salir vivo.",
      arc_es: "La reunión que te daba pánico. Entrás con miedo y salís pudiendo.",
      emoji: "😰",
      cardTheme: "peach",
      icon: "💻",
      survival: false,
      companionSetup_es: [
        "Llegó la reunión, la que a mí me tumbó la primera semana. Pero vos vas con ventaja.",
        "Te doy con qué entrar, opinar sin pelear y salir sin morir. Fresco que yo te cubro.",
      ],
      scenes: [
        {
          id: "u6-s1-entrar",
          order: 1,
          title_es: "Entrar a la llamada",
          scene_es: "Se abre el Meet. Cámaras, micrófonos y esa vocecita de \"¿sí me oyen?\".",
          icon: "🎧",
          setup_es: [
            "Lo primero en una llamada es el lío técnico: si te oyen, si te cortás.",
            "Con estas dos salís del apuro sin quedar callado esperando a ver qué pasa.",
          ],
          analogy_es: "Entrar a una videollamada es como subirte a una tarima: antes de hablar, revisás que el micrófono prenda. Mejor un \"¿me oyen?\" que cinco minutos en mudo.",
          chunks: [
            {
              id: "c-can-you-hear-me",
              en: "Can you hear me?",
              es: "¿Me escuchan?",
              sounds_es: "kan iú jíar mi",
              why_es: "El salvavidas del Meet. Es lo primero que soltás al entrar, cuando no sabés si el micrófono sirve. Mejor preguntar que hablar cinco minutos en mudo.",
              sayWhen_es: "Lo primero al entrar a una videollamada.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Can you listen me?", "Can you see me now?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-breaking-up",
              en: "Sorry, you're breaking up.",
              es: "Perdón, te estás cortando.",
              sounds_es: "sóri, iúr bréikin ap",
              why_es: "\"breaking up\" es que la voz te llega en pedacitos, cortada. Es la frase pa' cuando el internet traiciona y el otro suena como robot descompuesto.",
              sayWhen_es: "Cuando el otro se corta y no se le oye bien.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Sorry, you are breaking down.", "Sorry, I am breaking up."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
        {
          id: "u6-s2-opinar",
          order: 2,
          title_es: "Opinar sin pelear",
          scene_es: "Están decidiendo algo y te toca dar tu opinión.",
          icon: "🗣️",
          setup_es: [
            "Ahora te toca opinar: decir que sí, decir que no, pedir la palabra.",
            "El truco es opinar sin sonar patán. Acá el \"no\" se dice con guantes.",
          ],
          analogy_es: "Opinar en reunión es como manejar en trancón: no te le atravesás a nadie de golpe. Pedís el paso, avisás pa' dónde vas, y nadie pita.",
          chunks: [
            {
              id: "c-i-agree",
              en: "I agree with you.",
              es: "Estoy de acuerdo contigo.",
              sounds_es: "ái agrí güid iú",
              why_es: "\"agree\" carga su \"with\" pegado como una sombra: estás de acuerdo CON alguien, no \"a\" alguien. Van juntos siempre, como uña y mugre.",
              sayWhen_es: "Cuando estás de acuerdo con alguien.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["I agree to you.", "I am agree with you."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-not-sure",
              en: "I'm not sure about that.",
              es: "No estoy muy seguro de eso.",
              sounds_es: "áim not shúr abáut dat",
              why_es: "El \"no\" con guantes. Decir \"I disagree\" a secas suena a patán buscando pelea; con esta opinás distinto sin dañar el ambiente.",
              sayWhen_es: "Cuando no estás de acuerdo, pero sin pelear.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["I am not sure for that.", "I am not sure about you."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-can-i-say-something",
              en: "Can I say something?",
              es: "¿Puedo decir algo?",
              sounds_es: "kan ái séi sámzin",
              why_es: "Pa' pedir el turno sin atropellar a nadie. Es como levantar la mano, pero con la voz: pedís el paso y te lo dan.",
              sayWhen_es: "Pa' pedir la palabra sin interrumpir feo.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Can I say you something?", "Can I tell something?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
        {
          id: "u6-s3-acordar",
          order: 3,
          title_es: "Acordar y avanzar",
          scene_es: "Ya casi cierran. Toca acordar la hora y seguir con lo siguiente.",
          icon: "👍",
          setup_es: [
            "Para cerrar: aceptar un plan, anotar la hora y empujar pa' seguir.",
            "Frasecitas cortas que te hacen sonar como el que mueve la reunión.",
          ],
          analogy_es: "Cerrar acuerdos es como ponerle fecha a un parche: \"¿el viernes?\" \"listo\". Sin colgar la hora en algún lado, el plan se queda en el aire y no pasa nada.",
          chunks: [
            {
              id: "c-that-works-for-me",
              en: "That works for me.",
              es: "Eso me sirve.",
              sounds_es: "dat guórks for mi",
              why_es: "Pa' aceptar una hora o un plan sin repetir todo el cuento. Cortica y quedás profesional: es el \"por mí, listo\" de la oficina.",
              sayWhen_es: "Cuando aceptás una hora o un plan.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["That works to me.", "That work for me."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-meeting-at-3",
              en: "We have a meeting at 3.",
              es: "Tenemos reunión a las 3.",
              sounds_es: "güi jav a mítin at zri",
              why_es: "\"at\" + la hora es el clavo donde colgás el horario: at 3, at noon, at 10. Siempre el mismo clavo, solo cambiás lo que colgás.",
              sayWhen_es: "Pa' avisar la hora de una reunión.",
              who_es: "con cualquiera (seguro)",
              frame: "We have a meeting at ___.",
              swaps: ["3", "noon", "10"],
              distractors_es: ["We have a meeting in 3.", "We have a meeting on 3."],
              cognateHook_es: "Ojo con \"meeting\": suena a \"mitin\", pero es una reunión de trabajo, no un mitin político.",
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-lets-move-on",
              en: "Let's move on.",
              es: "Sigamos con lo siguiente.",
              sounds_es: "lets muv on",
              why_es: "Cuando la reunión se queda pegada en un punto, esta es el empujoncito pa' avanzar. Como cuando la fila no camina y alguien dice \"bueno, sigamos\".",
              sayWhen_es: "Cuando la reunión se queda pegada y toca avanzar.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Let's move out.", "Let's go on."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
      ],
      task: {
        id: "u6-task",
        intro_es: "Bueno, la reunión temida. Respirá: acá tenés con qué sobrevivirla…",
        steps: [
          {
            goal_es: "Entrás a la llamada y no sabés si te oyen. Preguntá.",
            answerChunkId: "c-can-you-hear-me",
            reaction_es: "¡Eso! Mejor preguntar que hablar en mudo cinco minutos.",
          },
          {
            goal_es: "Alguien propone algo y te parece bien. Decíle que estás de acuerdo.",
            answerChunkId: "c-i-agree",
            reaction_es: "Perfecto, con el \"with\" bien pegado. Nunca \"agree to\".",
          },
          {
            goal_es: "La reunión se quedó pegada. Empujá pa' seguir.",
            answerChunkId: "c-lets-move-on",
            reaction_es: "Eso, parce. Ya sonás como el que maneja la reunión.",
          },
        ],
        done_es: "Ya sabés SOBREVIVIR LA REUNIÓN SIN MIEDO. ✓",
      },
    },
    {
      id: "u7-tareas",
      order: 7,
      title_es: "Tareas, quedar y cerrar la semana",
      subtitle_es: "Cumplir y despedirte como pro.",
      arc_es: "Cierra la semana. Ya no sos el nuevo asustado: ya sos del parche.",
      emoji: "🎉",
      cardTheme: "blue",
      icon: "📋",
      survival: false,
      companionSetup_es: [
        "Última milla: te dejan tareas, mandás un correo y cerrás la semana.",
        "Con estas quedás como el que cumple. Y el viernes te despedís ya siendo del parche.",
      ],
      scenes: [
        {
          id: "u7-s1-tareas",
          order: 1,
          title_es: "Tareas y tiempos",
          scene_es: "Te empiezan a caer tareas con sus fechas. Toca responder bien.",
          icon: "⏰",
          setup_es: [
            "Te van a dejar tareas y a preguntarte por tiempos. Hay que responder parado.",
            "Comprometerte, preguntar la fecha, pedir más tiempo si toca: todo sin drama.",
          ],
          analogy_es: "Responder por una tarea es como recibir un balón: o lo agarrás y decís \"yo la llevo\", o lo dejás caer y quedás mal. Mejor un \"yo me encargo\" claro.",
          chunks: [
            {
              id: "c-ill-do-it-now",
              en: "I'll do it now.",
              es: "Lo hago ahora.",
              sounds_es: "áil du it náu",
              why_es: "\"I'll\" es \"yo me encargo\", dicho de una. Corta y decidida: con eso quedás como el que resuelve, no el que se hace el bobo.",
              sayWhen_es: "Cuando te encargan algo y lo asumís de una.",
              who_es: "con cualquiera (seguro)",
              frame: "I'll ___.",
              swaps: ["do it now", "check", "call"],
              distractors_es: ["I do it now.", "I'll make it now."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-send-after-lunch",
              en: "I'll send it after lunch.",
              es: "Lo mando después de almuerzo.",
              sounds_es: "áil send it áfter lanch",
              why_es: "Prometés algo cortico sin enredarte: \"lo mando después de ___\". Le colgás el momento (lunch, the call) y ya sabe cuándo esperarlo.",
              sayWhen_es: "Pa' prometer algo con un tiempo cortico.",
              who_es: "con cualquiera (seguro)",
              frame: "I'll send it after ___.",
              swaps: ["lunch", "the call", "the meeting"],
              distractors_es: ["I send it after lunch.", "I'll send it before lunch."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-when-deadline",
              en: "When is the deadline?",
              es: "¿Cuándo es la entrega?",
              sounds_es: "güén is de dédlain",
              why_es: "Preguntar la fecha es de pro, no de intenso. Mejor saber pa' cuándo es y organizarte, que entregar tarde y quedar mal.",
              sayWhen_es: "Pa' preguntar la fecha de entrega.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["When is the meeting?", "What is the deadline?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-need-more-time",
              en: "I need more time.",
              es: "Necesito más tiempo.",
              sounds_es: "ái níid mor táim",
              why_es: "Pedir más tiempo a tiempo es mil veces mejor que fallar la entrega callado. Se dice sin drama: avisar temprano es de responsable, no de flojo.",
              sayWhen_es: "Cuando ves que no alcanzás y pedís tiempo.",
              who_es: "con el jefe",
              frame: null,
              swaps: null,
              distractors_es: ["I need more times.", "I want more time now."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-its-ready",
              en: "It's ready.",
              es: "Ya está listo.",
              sounds_es: "its rédi",
              why_es: "Cortica pa' avisar que terminaste. Dos palabritas que suenan a que cumplís: soltás eso y el otro respira tranquilo.",
              sayWhen_es: "Pa' avisar que terminaste algo.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["It's finish.", "I'm ready."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
        {
          id: "u7-s2-correo",
          order: 2,
          title_es: "El correo básico",
          scene_es: "Toca mandar tu primer correo. Menos susto: casi todo son fórmulas.",
          icon: "📧",
          setup_es: [
            "El correo asusta menos de lo que creés: el 80% son fórmulas armadas.",
            "Una pa' abrir, una pa' el cuerpo, una pa' cerrar. Copiás, pegás y ya.",
          ],
          analogy_es: "Un correo es como armar con bloques de lego: no inventás cada pieza, encajás las que ya vienen hechas. Abrís, decís lo tuyo, cerrás.",
          chunks: [
            {
              id: "c-get-back-to-you",
              en: "Let me check and get back to you.",
              es: "Déjame revisar y te aviso.",
              sounds_es: "let mi chek and get bak tu iú",
              why_es: "La frase mágica pa' cuando no sabés la respuesta. En vez de inventar, decís \"déjame ver y te aviso\": ganás tiempo y quedás responsable, no perdido.",
              sayWhen_es: "Cuando no tenés la respuesta y ganás tiempo.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Let me check and come back to you.", "Let me see and get back for you."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-thanks-for-email",
              en: "Thanks for your email.",
              es: "Gracias por tu correo.",
              sounds_es: "zanks for iór ímeil",
              why_es: "Fórmula fija pa' abrir un correo. El 80% de un mail son fórmulas armadas: no las inventás, las copiás y pegás como ladrillos.",
              sayWhen_es: "Pa' abrir o responder un correo.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Thanks by your email.", "Thanks for you email."],
              cognateHook_es: "\"email\" es igual que en español, esa ni la tenés que estudiar.",
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-best-regards",
              en: "Best regards.",
              es: "Saludos cordiales.",
              sounds_es: "best rigárds",
              why_es: "El cierre fijo del mail, el candado del final. Con \"Best regards\" cerrás cualquier correo y quedás formal, sea al jefe o al cliente.",
              sayWhen_es: "Pa' cerrar cualquier correo.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Better regards.", "Best regard."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
        {
          id: "u7-s3-despedir",
          order: 3,
          title_es: "Despedir la semana",
          scene_es: "Viernes en la tarde. Cerrás tu primera semana en la empresa.",
          icon: "👋",
          setup_es: [
            "Llegó el viernes de tu primera semana. Toca despedirse bonito.",
            "Cerrás con quien conociste y quedás pa' el lunes. Lo lograste, parce.",
          ],
          analogy_es: "Despedir la semana es como el abrazo de salida de un paseo: cerrás bonito con los que conociste y quedás invitado pa' la próxima. Eso es ya ser del parche.",
          chunks: [
            {
              id: "c-nice-meeting-you",
              en: "It was nice meeting you.",
              es: "Fue un gusto conocerte.",
              sounds_es: "it guas náis mítin iú",
              why_es: "Es el \"nice to meet you\" pero al despedirte, mirando pa' atrás. Cuando ya conociste a alguien y te vas, cerrás bonito con esta.",
              sayWhen_es: "Al despedirte de alguien que conociste esta semana.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["It is nice meeting you.", "It was nice met you."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-see-you-monday",
              en: "See you on Monday.",
              es: "Nos vemos el lunes.",
              sounds_es: "síi iú on mándei",
              why_es: "El chao del viernes. Misma fórmula \"See you\" + cuándo, pero con el lunes colgado: te despedís sabiendo que la próxima es después del finde.",
              sayWhen_es: "El viernes, despidiéndote hasta el lunes.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["See you in Monday.", "See you on Sunday."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
      ],
      task: {
        id: "u7-task",
        intro_es: "Última milla: te dejan una tarea y toca cerrar la semana bien. Vamos…",
        steps: [
          {
            goal_es: "El jefe te deja algo urgente. Decíle que lo hacés ya.",
            answerChunkId: "c-ill-do-it-now",
            reaction_es: "¡Eso! Quedaste como el que resuelve.",
          },
          {
            goal_es: "No sabés la respuesta todavía. Decí que revisás y avisás.",
            answerChunkId: "c-get-back-to-you",
            reaction_es: "Perfecto. Ganaste tiempo sin quedar perdido.",
          },
          {
            goal_es: "Es viernes y conociste gente nueva. Despedí la semana.",
            answerChunkId: "c-see-you-monday",
            reaction_es: "Sobreviviste tu primera semana, parce. En serio. Ya sos del parche.",
          },
        ],
        done_es: "Ya sabés CERRAR LA SEMANA COMO UN PRO. ✓",
      },
    },
  ],
};
