/* CONTENIDO DEL CURSO A1 · OFICINA — generado desde el legacy
   (public/js/a1-office-content.js, window.A1_OFFICE) y tipado contra el
   contrato compartido de '@/content/a1/tipos'.

   Los TEXTOS son VERBATIM: son la voz de Alfred, ya aprobada. Si hay que
   cambiar una tilde, se cambia acá y en ningún otro lado — la UI no reescribe
   nada del contenido, solo lo pinta.

   Los ids de chunk son la LLAVE del SRS (rodeo_a1_srs) y de las tareas
   (answerChunkId): renombrar uno le borra el progreso a quien ya lo tenía.
   Por eso las cuatro frases pre-A1 que se fueron al Tramo 0 se MUDARON con el
   id intacto: quien las tenía en caja 4 las sigue teniendo, ahora en el T0.
   7 unidades · 18 escenas · 59 chunks propios (+1 que comparte con el T0). */

import type { A1Chunk, A1Course } from '@/content/a1/tipos';

/* La pregunta del baño se enseñaba DOS veces: acá en u5 y otra vez en el Tramo
   0 con el id `c-t0-where-bathroom`. Mismo inglés, dos ids = dos entradas
   Leitner que vencen por separado para siempre, que es justo lo que el propio
   contenido prohíbe. Ahora hay un solo objeto y el Tramo 0 lo importa: un chunk
   puede vivir en dos escenas sin problema (construirIndice lo indexa por id y
   nuevos() deduplica con un Set).

   El id viejo se queda porque es el que tiene progreso guardado. El TEXTO, en
   cambio, es el del Tramo 0: "está" en vez del "queda" colombiano, "uér" en vez
   de "güér" (que en ortografía española se lee /gwer/), y un why_es que enseña
   el molde sin amarrarlo a la oficina. Los `swaps` juntan los dos mundos:
   primero los del viaje, después los de la oficina. */
export const C_WHERE_IS_BATHROOM: A1Chunk = {
  id: "c-where-is-bathroom",
  en: "Where is the bathroom?",
  es: "¿Dónde está el baño?",
  sounds_es: "uér is de bázrum",
  why_es: "La pregunta más hecha del planeta. Y con \"Where is the ___?\" ya preguntas por cualquier cosa: la salida, el taxi, la impresora.",
  sayWhen_es: "En todas partes, siempre.",
  who_es: "con cualquiera (seguro)",
  frame: "Where is the ___?",
  swaps: ["bathroom", "exit", "taxi", "printer", "kitchen"],
  distractors_es: ["Where the bathroom?", "Where are the bathroom?"],
  cognateHook_es: null,
  forms: null,
  audio: null,
  /* Se queda en false a propósito, aunque la versión del T0 la traía en true:
     construirIndice hace `ix.supervivencia.push(c)` SIN deduplicar por id, así
     que un chunk compartido entre dos escenas saldría dos veces en la HojaPánico
     (y con la misma `key` de React). Cuando el índice deduplique, esto puede
     volver a true. */
  survival: false,
};

export const A1_CURSO: A1Course = {
  version: 1,
  companion: {
    id: "alfred",
    name: "Alfred",
    fullName: "Alfredo",
    avatarInitial: "A",
    cardTheme: "peach",
    origin_es: "Lleva un año en la empresa; ya se sabe el terreno.",
    tagline_es: "Tu colega en la oficina nueva.",
    intro_es: [
      "¡Ey! Tú eres el nuevo, ¿cierto? Yo soy Alfred, llevo un año acá.",
      "Tranquilo que yo te acompaño esta semana. A mí nadie me dijo nada y la sufrí.",
      "Acá no hay examen ni nadie te oye. Te equivocas las veces que quieras. Ese es el punto.",
      "No vas a aprender inglés de libro. Vas a aprender lo que se dice el lunes a las 8.",
    ],
  },
  cognates: [
    { en: "information", es: "información", falseHook_es: null },
    { en: "professional", es: "profesional", falseHook_es: null },
    { en: "project", es: "proyecto", falseHook_es: null },
    { en: "client", es: "cliente", falseHook_es: null },
    { en: "office", es: "oficina", falseHook_es: null },
    { en: "experience", es: "experiencia", falseHook_es: null },
    { en: "company", es: "compañía", falseHook_es: null },
    { en: "communication", es: "comunicación", falseHook_es: null },
    { en: "presentation", es: "presentación", falseHook_es: null },
    { en: "position", es: "posición", falseHook_es: null },
    { en: "department", es: "departamento", falseHook_es: null },
    { en: "opportunity", es: "oportunidad", falseHook_es: null },
    { en: "important", es: "importante", falseHook_es: null },
    { en: "minute", es: "minuto", falseHook_es: null },
    { en: "problem", es: "problema", falseHook_es: null },
    {
      en: "meeting",
      es: "reunión",
      falseHook_es: "te suena a \"mitin\", úsalo de gancho pa' acordarte — pero ojo, un meeting es una reunión de trabajo, no un mitin político.",
    },
  ],
  units: [
    {
      id: "u1-llegar",
      order: 1,
      title_es: "Tu primer día: llegar y saludar",
      subtitle_es: "Entrar sin quedar mudo.",
      arc_es: "Llegas asustado. Alfred te adopta.",
      emoji: "😰",
      cardTheme: "blue",
      icon: "🚶",
      survival: false,
      companionSetup_es: [
        "Bueno, primer día. Respira. Hoy solo hay que sobrevivir la llegada.",
        "Te enseño el saludo, cómo decir que eres nuevo, y cómo despedirte.",
      ],
      scenes: [
        {
          id: "u1-s1-pasillo",
          order: 1,
          title_es: "El saludo del pasillo",
          scene_es: "Te cruzas con tu jefe en el pasillo. Toca saludar.",
          icon: "🌅",
          setup_es: [
            "Ojo, ahí viene el jefe por el pasillo. En español le dirías \"buenas, ¿cómo va?\".",
            "En inglés hay una fórmula, toda junta. Te la muestro.",
          ],
          analogy_es: "Piensa en el saludo como abrir la puerta: primero saludas y ahí sí entras al tema. Nadie negocia sin saludar.",
          chunks: [
            {
              id: "c-good-morning",
              en: "Good morning.",
              es: "Buenos días.",
              sounds_es: "gud mórnin",
              why_es: "El saludo base, el más seguro de todos. Con eso nunca quedas mal, se lo tiras a cualquiera.",
              sayWhen_es: "Al llegar en la mañana, con cualquiera.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Good night.", "Good luck."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-goodmorning-everyone",
              en: "Good morning, everyone.",
              es: "Buenos días a todos.",
              sounds_es: "gud mórnin, évriwan",
              why_es: "\"everyone\" es tu \"a todos\" sin nombrar a nadie uno por uno. Lo sueltas al entrar y quedaste bien con toda la sala.",
              sayWhen_es: "Al entrar a una sala o al equipo.",
              who_es: "con cualquiera (seguro)",
              frame: "Good morning, ___.",
              swaps: ["everyone", "Sarah", "team"],
              distractors_es: ["Good night, everyone.", "See you, everyone."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-hows-it-going",
              en: "Hi, how's it going?",
              es: "Hola, ¿cómo va?",
              sounds_es: "jái, jáus it góin",
              why_es: "Es el \"¿bien o qué?\" de allá. No esperan tu biografía: se contesta \"good, you?\" y ya. Con un compañero del cubículo, no con el CEO en el ascensor.",
              sayWhen_es: "Saludo casual, de pasada, con un compañero.",
              who_es: "con un compañero",
              frame: null,
              swaps: null,
              distractors_es: ["Hi, where is it?", "Hi, how much is it?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
        /* Acá vivía `u1-s2-conocer`, y tenía exactamente dos frases:
           "Nice to meet you." y "What's your name?". Las dos son pre-A1 puro y
           se mudaron al Tramo 0 (t0-preguntas) con su id intacto.

           La escena NO podía quedarse vacía. Con `chunks: []`, proximaEscena()
           la devuelve para siempre, abrirUnidad() tostea "Esta escena todavía
           no tiene frases" y no navega, y escenasHechas('u1-llegar') nunca da
           true: u1-llegar queda imposible de terminar, para siempre. Un
           callejón sin salida permanente por dos frases que se fueron.

           Por eso se borra la escena entera y la unidad pasa de 3 escenas a 2.
           El `order: 3` de la que sigue se deja como está: solo se usa como
           clave de ordenamiento (el sort de `nuevos()`) y el hueco no molesta. */
        {
          id: "u1-s3-presentarte",
          order: 3,
          title_es: "Decir quién eres y despedirte",
          scene_es: "Te presentan y, al rato, se acaba el día.",
          /* Era 🪪 (U+1FAAA, Emoji 14.0 · 2021): en el Chrome de Windows 10 sale
             cuadrito vacío, porque la Segoe UI Emoji de Win10 llega hasta 13.1.
             📛 es Emoji 1.0 y dice lo mismo: el gafete con tu nombre. */
          icon: "📛",
          setup_es: [
            "Primero tu escudo de nuevo, que nadie te va a exigir de más.",
            "Y al final, el chao del día, suavecito.",
          ],
          analogy_es: "Decir que eres nuevo no es debilidad: es un escudo. El que avisa que va llegando recibe ayuda en vez de exigencia.",
          chunks: [
            /* `c-im-new-here` se mudó al Tramo 0 (t0-ser-estar): es un "I'm ___"
               y ahí es donde se enseña la pieza. La escena queda con 2 frases,
               que siguen siendo contenido suficiente.
               La tarea `u1-task` lo sigue usando como answerChunkId y eso está
               bien: tarea.tsx resuelve por el índice GLOBAL del catálogo
               (indice.chunk), no por la unidad, así que el paso sigue existiendo
               mientras el Tramo 0 esté cableado. */
            {
              id: "c-have-a-good-day",
              en: "Have a good day.",
              es: "Que tengas buen día.",
              sounds_es: "jav a gud déi",
              why_es: "El cierre amable de salida. Se regala fácil y cae bien; no cuesta nada y te deja bien parado.",
              sayWhen_es: "Al despedirte, saliendo.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Have a good name.", "Give a good day."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-see-you-tomorrow",
              en: "See you tomorrow.",
              es: "Nos vemos mañana.",
              sounds_es: "síi iú tumórou",
              why_es: "\"See you\" + cuándo: tomorrow, on Monday, later. El chao de oficina; cambias la colita y ya.",
              sayWhen_es: "Al salir, si mañana vuelves a ver a la persona.",
              who_es: "con cualquiera (seguro)",
              frame: "See you ___.",
              swaps: ["tomorrow", "on Monday", "later"],
              distractors_es: ["See you never.", "I see you tomorrow morning early."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
      ],
      task: {
        id: "u1-task",
        intro_es: "Listo. Ahora sobrevive tu primera mañana. Vas entrando…",
        steps: [
          {
            goal_es: "Te cruzas al de recepción y a medio equipo. Salúdalos a todos de una.",
            answerChunkId: "c-goodmorning-everyone",
            reaction_es: "¡Eso! Entraste como si nada.",
          },
          {
            goal_es: "Te presentan a tu jefa. Dile que eres nuevo.",
            answerChunkId: "c-im-new-here",
            reaction_es: "Perfecto, con eso bajas expectativas y te ayudan.",
          },
          {
            goal_es: "Se acaba el día. Despídete para mañana.",
            answerChunkId: "c-see-you-tomorrow",
            reaction_es: "Sobreviviste el día 1. En serio.",
          },
        ],
        done_es: "Ya sabes LLEGAR A LA OFICINA. ✓",
      },
    },
    {
      id: "u2-supervivencia",
      order: 2,
      title_es: "Tu kit de supervivencia",
      subtitle_es: "Las que te salvan de cualquier lío.",
      arc_es: "Ya no entiendes algo. En vez de asentir y hacer la tarea mala, aprendes a pedir.",
      emoji: "🪂",
      cardTheme: "yellow",
      /* Era 🛟 (U+1F6DF, Emoji 14.0 · 2021) — mismo caso que el 🪪 de u1: tofu
         en Windows 10. ⛑️ es de 2017 y significa lo mismo, rescate. */
      icon: "⛑️",
      survival: true,
      companionSetup_es: [
        "Estas son las que te salvan de cualquier lío. Apréndetelas primero y ya nada te asusta.",
        "Con estas cinco, aunque no entiendas nada, no te ahogas. Son tu red.",
      ],
      scenes: [
        {
          id: "u2-s1-no-entendiste",
          order: 1,
          title_es: "No entendiste",
          scene_es: "Te hablan en inglés y se te fue el hilo. Pasa.",
          icon: "🙉",
          setup_es: [
            "Te hablaron y no cazaste nada. Tranquilo, a todos nos pasa.",
            "Nadie se enoja si pides que repitan: prefieren repetírtelo a que hagas algo mal.",
          ],
          analogy_es: "Pedir que repitan es de vivos, no de bobos. Es el botón de rebobinar: lo aprietas sin pena y listo.",
          chunks: [
            {
              id: "c-dont-understand",
              en: "Sorry, I don't understand.",
              es: "Perdón, no entiendo.",
              sounds_es: "sóri, ái dont anderstánd",
              why_es: "Decir esto es de vivos, no de bobos. Nadie se enoja: prefieren repetirte a que hagas algo mal.",
              sayWhen_es: "Cuando no entendiste y toca decirlo.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Sorry, I don't listen.", "Sorry, I understand nothing here."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: true,
            },
            {
              id: "c-repeat",
              en: "Can you repeat that, please?",
              es: "¿Puedes repetir eso, por favor?",
              sounds_es: "kan iú ripít dat, plís",
              why_es: "El botón de rebobinar hablado. El \"please\" al final es el aceitito para que no suene grosero.",
              sayWhen_es: "Cuando necesitas que repitan algo.",
              who_es: "con cualquiera (seguro)",
              frame: "Can you ___, please?",
              swaps: ["repeat that", "speak slowly", "help me"],
              distractors_es: ["Can you repeat that, thanks?", "You repeat that now."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: true,
            },
            {
              id: "c-speak-slowly",
              en: "Can you speak slowly, please?",
              es: "¿Puedes hablar despacio, por favor?",
              sounds_es: "kan iú spík slóuli, plís",
              why_es: "Nadie se ofende si pides despacio. Al contrario: prefieren repetírtelo a que hagas algo mal.",
              sayWhen_es: "Cuando hablan muy rápido.",
              who_es: "con cualquiera (seguro)",
              frame: "Can you ___, please?",
              swaps: ["speak slowly", "repeat that", "help me"],
              distractors_es: ["Can you speak slow, please?", "Speak slowly you, please?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: true,
            },
            {
              id: "c-didnt-catch",
              en: "Sorry, I didn't catch that.",
              es: "Perdón, no alcancé a oír.",
              sounds_es: "sóri, ái dídnt kach dat",
              why_es: "\"catch\" es atrapar: no atrapaste la pelota de lo que dijeron. Suena mejor que \"I don't understand\" porque no admite que fallaste tú.",
              sayWhen_es: "Cuando no alcanzaste a oír bien.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Sorry, I didn't hear you good.", "Sorry, I don't catch."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: true,
            },
          ],
        },
        {
          id: "u2-s2-falta-palabra",
          order: 2,
          title_es: "Te falta una palabra",
          scene_es: "Cae una palabra que no conoces y te trabas.",
          icon: "🗺️",
          setup_es: [
            "Cuando te falta una palabra, preguntas en vez de congelarte.",
            "Y si necesitas una pausita o una mano, también se pide sin drama.",
          ],
          analogy_es: "Preguntar qué significa algo es como pedir el mapa cuando estás perdido: no es rendirse, es lo que hace el que sabe moverse.",
          chunks: [
            {
              id: "c-what-does-that-mean",
              en: "What does that mean?",
              es: "¿Qué significa eso?",
              sounds_es: "guát das dat mín",
              why_es: "Tu comodín cuando cae una palabra que no conoces. Preguntar es de vivos, no de bobos.",
              sayWhen_es: "Cuando cae una palabra que no conoces.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["What does that means?", "What that mean does?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-how-do-you-say",
              en: "How do you say this in English?",
              es: "¿Cómo se dice esto en inglés?",
              sounds_es: "jáu du iú séi dis in ínglish",
              why_es: "Cuando te falta la palabra, preguntas en vez de congelarte. Es de vivos, no de bobos.",
              sayWhen_es: "Cuando te falta la palabra en inglés.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["How you say this in English?", "How do you say this on English?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-help-me-with-this",
              en: "Can you help me with this?",
              es: "¿Me ayudas con esto?",
              sounds_es: "kan iú jelp mi güid dis",
              why_es: "\"help me WITH algo\": el \"with\" es la mano que señala QUÉ. Pides ayuda apuntando al problema.",
              sayWhen_es: "Cuando necesitas una mano con algo.",
              who_es: "con cualquiera (seguro)",
              frame: "Can you help me with ___?",
              swaps: ["this", "the report", "the printer"],
              distractors_es: ["Can you help me on this?", "Can you help this with me?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: true,
            },
            {
              id: "c-one-moment",
              en: "One moment, please.",
              es: "Un momento, por favor.",
              sounds_es: "guán móument, plís",
              why_es: "Pa' pedir una pausita sin enredarte. Ganas dos segundos y no te ahogas.",
              sayWhen_es: "Cuando necesitas una pausita.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["One minute, thanks.", "A moment, one please."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
      ],
      task: {
        id: "u2-task",
        intro_es: "Bueno, ahora imaginate en una reunión y no entiendes nada. Saca tus salvavidas…",
        steps: [
          {
            goal_es: "El jefe dijo algo rapidísimo. Pídele que lo repita.",
            answerChunkId: "c-repeat",
            reaction_es: "¡Eso! Y nadie se enojó, ¿viste?",
          },
          {
            goal_es: "Habla como una metralleta. Pídele que hable despacio.",
            answerChunkId: "c-speak-slowly",
            reaction_es: "De una. Ahí ya lo agarras todo.",
          },
          {
            goal_es: "Cayó una palabra rara. Pregunta qué significa.",
            answerChunkId: "c-what-does-that-mean",
            reaction_es: "Perfecto. Preguntar es de vivos.",
          },
        ],
        done_es: "Ya tienes tu KIT DE SUPERVIVENCIA. ✓ Con esas no te ahogas.",
      },
    },
    {
      id: "u3-presentarte",
      order: 3,
      title_es: "Preséntate y conoce al equipo",
      subtitle_es: "Decir quién eres sin trabarte.",
      arc_es: "Ya no estás tan asustado. Te presentas y empiezas a pertenecer.",
      emoji: "👋",
      cardTheme: "lavender",
      icon: "👥",
      survival: false,
      companionSetup_es: [
        "Hoy te presento con el equipo. Suena feo, pero con dos o tres frases quedas.",
        "Aprendes a decir qué haces, de dónde eres, y a devolver la pregunta pa' que no se muera la charla.",
      ],
      scenes: [
        {
          id: "u3-s1-equipo",
          order: 1,
          title_es: "Te presentan al equipo",
          scene_es: "Alfred te lleva donde el equipo. Te van a saludar uno por uno.",
          icon: "🤝",
          setup_es: [
            "Te van a presentar con el equipo, uno por uno. Tranquilo, es rapidito.",
            "Con devolver el saludo y hacer una preguntita, ya quedas como gente.",
          ],
          analogy_es: "Conocer al equipo es como llegar a un asado ajeno: saludas, preguntas algo y ya dejas de ser el desconocido del rincón.",
          chunks: [
            {
              id: "c-nice-to-meet-you-too",
              en: "Nice to meet you too.",
              es: "Igualmente, mucho gusto.",
              sounds_es: "náis tu mít iú tú",
              why_es: "Cuando te dicen \"nice to meet you\", tú rebotas lo mismo con un \"too\" pegado al final. Es el \"igualmente\" de toda la vida: la pelota que te tiran, la devuelves.",
              sayWhen_es: "Cuando te dicen \"nice to meet you\" y respondes.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Nice to see you too.", "Good to meet you first."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-what-do-you-do",
              en: "What do you do here?",
              es: "¿Qué haces aquí?",
              sounds_es: "guát du iú du jíar",
              why_es: "Es el \"¿y tú en qué andas?\" de oficina. Rompe el hielo sin meterte en la vida de nadie: preguntas por el trabajo, no por el chisme.",
              sayWhen_es: "Pa' preguntarle a alguien en qué trabaja.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["What do you have here?", "Where do you go here?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-where-do-you-work",
              en: "Where do you work?",
              es: "¿Dónde trabajas?",
              sounds_es: "güér du iú guórk",
              why_es: "Devuelves la pregunta pa' que la charla no se muera. El small talk es como el ping-pong: si no la devuelves, se cae la bolita y te quedas mudo.",
              sayWhen_es: "Pa' devolver la pregunta y seguir la charla.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Where do you live?", "When do you work?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-how-long-worked",
              en: "How long have you worked here?",
              es: "¿Cuánto llevas trabajando aquí?",
              sounds_es: "jáu long jav iú guórkt jíar",
              why_es: "Con esta muestras interés sin ser metido. A la gente le encanta contar su propia historia: le abres la puerta y solita se pone a hablar.",
              sayWhen_es: "Cuando quieres mostrar interés en la otra persona.",
              who_es: "con un compañero",
              frame: null,
              swaps: null,
              distractors_es: ["How long is the work?", "How many work here?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
        {
          id: "u3-s2-quien-eres",
          order: 2,
          title_es: "Qué haces y de dónde eres",
          scene_es: "Te preguntan en qué trabajas y de dónde vienes.",
          icon: "🌎",
          setup_es: [
            "Ahora te toca hablar un poquito de ti: tu equipo, tu país.",
            "Son moldes: le metes tu área o tu país y listo, no hay que inventar nada.",
          ],
          analogy_es: "Contar qué haces es como ponerte el uniforme del equipo: con una frase la gente ya sabe dónde encajas y en qué te pueden buscar.",
          chunks: [
            {
              id: "c-work-in-sales",
              en: "I work in the sales team.",
              es: "Trabajo en el equipo de ventas.",
              sounds_es: "ái guórk in de séils tim",
              why_es: "Es tu molde pa' decir de qué equipo eres: le metes tu área y listo. Como el letrerito del escritorio que dice dónde encajas.",
              sayWhen_es: "Cuando te preguntan a qué te dedicas.",
              who_es: "con cualquiera (seguro)",
              frame: "I work in ___.",
              swaps: ["the sales team", "sales", "support"],
              distractors_es: ["I like the sales team.", "I have a sales meeting."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-on-design-team",
              en: "I'm on the design team.",
              es: "Estoy en el equipo de diseño.",
              sounds_es: "áim on de disáin tim",
              why_es: "\"on the ___ team\" es como decir \"soy de la selección de…\". No es que trabajes cerca del equipo: es que eres del equipo, juegas ahí.",
              sayWhen_es: "Cuando dices de qué equipo eres.",
              who_es: "con cualquiera (seguro)",
              frame: "I'm on the ___ team.",
              swaps: ["design", "sales", "support"],
              distractors_es: ["I like the design team.", "I want the design team."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            /* `c-im-from-colombia` se mudó al Tramo 0 (t0-ser-estar), junto al
               resto de los "I'm ___". La escena queda con 3 frases. */
            {
              id: "c-my-first-week",
              en: "This is my first week.",
              es: "Esta es mi primera semana.",
              sounds_es: "dis is mái ferst güík",
              why_es: "Es el escudo de nuevo, versión semana: avisas que vas llegando y la gente te da tiempo y paciencia en vez de exigirte de una.",
              sayWhen_es: "Cuando quieres que te tengan paciencia de nuevo.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["This is my first day.", "This is my last week."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
      ],
      task: {
        id: "u3-task",
        intro_es: "Bueno, te toca presentarte con el equipo. Sin miedo, que ya tienes con qué…",
        steps: [
          {
            goal_es: "Te presentan a una compañera. Devolvele el saludo.",
            answerChunkId: "c-nice-to-meet-you-too",
            reaction_es: "¡Eso! Con el \"too\" quedaste como gente.",
          },
          {
            goal_es: "Te preguntan en qué andas. Di que trabajas en ventas.",
            answerChunkId: "c-work-in-sales",
            reaction_es: "De una. Ya saben de qué equipo eres.",
          },
          {
            goal_es: "Quieres saber de la otra persona. Pregúntale dónde trabaja.",
            answerChunkId: "c-where-do-you-work",
            reaction_es: "Eso, devolviste la pregunta. Así no se muere la charla.",
          },
        ],
        done_es: "Ya sabes PRESENTARTE Y CONOCER AL EQUIPO. ✓",
      },
    },
    {
      id: "u4-smalltalk",
      order: 4,
      title_es: "Small talk y cortesía",
      subtitle_es: "La charlita que te hace del grupo.",
      arc_es: "Descubres que la charla boba del café es la que te mete en el grupo.",
      emoji: "☕",
      cardTheme: "green",
      icon: "💬",
      survival: false,
      companionSetup_es: [
        "Bienvenido al small talk: esa charlita boba del cafecito que acá no es opcional.",
        "Es el aceitito social. Con estas frasecitas dejas de ser el mudo del rincón.",
      ],
      scenes: [
        {
          id: "u4-s1-lunes",
          order: 1,
          title_es: "El lunes en la mañana",
          scene_es: "Lunes, 8 a.m. Todos con el cafecito preguntando por el finde.",
          icon: "☀️",
          setup_es: [
            "Es lunes y arranca el ritual del cafecito: \"¿cómo te fue el finde?\".",
            "No es chisme, es el saludo largo. El que no lo hace se ve raro.",
          ],
          /* Era "calentar el carro… dos minuticos": "carro" toma partido en el
             pleito carro/coche y el diminutivo en -ico marca país. "El motor"
             no es de nadie y la imagen queda igual. */
          analogy_es: "El small talk del lunes es como calentar el motor antes de arrancar: dos minutitos de charla boba y ya la relación anda suave todo el día.",
          chunks: [
            {
              id: "c-how-was-weekend",
              en: "How was your weekend?",
              es: "¿Cómo estuvo tu finde?",
              sounds_es: "jáu guas iór güíkend",
              why_es: "El clásico del lunes. Acá el small talk no es opcional: es el aceitito que hace que la máquina de la oficina no chirríe. Preguntas y ya eres gente.",
              sayWhen_es: "El lunes, pa' preguntar por el fin de semana.",
              who_es: "con cualquiera (seguro)",
              frame: "How was your ___?",
              swaps: ["weekend", "trip", "call"],
              distractors_es: ["How is your work?", "How was your week?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-how-are-you-today",
              en: "How are you today?",
              es: "¿Cómo estás hoy?",
              sounds_es: "jáu ar iú tudéi",
              why_es: "Saludo seguro con quien sea. Ojo: no es interrogatorio de verdad — contestan \"good, thanks\" y tú igual. Es un apretón de manos con palabras, no una consulta médica.",
              sayWhen_es: "Saludo del día, con cualquiera.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["How old are you today?", "How was you today?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-excited-to-be-here",
              en: "I'm excited to be here.",
              es: "Me alegra estar aquí.",
              sounds_es: "áim eksáited tu bi jíar",
              why_es: "Se la tiras al jefe o al equipo el primer día y quedas como oro. Es la sonrisa hecha frase: dice que llegas con ganas, no muerto del susto.",
              sayWhen_es: "Tu primer día, con el jefe o el equipo.",
              who_es: "con el jefe",
              frame: null,
              swaps: null,
              distractors_es: ["I am tired to be here.", "I am excited for here."],
              cognateHook_es: "Ojo: \"excited\" no es \"excitado\" (esa en español es otra cosa). Acá es \"emocionado\", \"con ganas\".",
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
        {
          id: "u4-s2-cortesia",
          order: 2,
          title_es: "Gracias y de nada",
          scene_es: "Alguien te hace un favor. Toca agradecer y saber responder.",
          icon: "🙏",
          setup_es: [
            "Te van a hacer favores y a agradecerte. Hay que saber ir y volver.",
            "Un \"gracias\" fuerte y un \"de nada\" bien puesto: con eso quedas fino.",
          ],
          analogy_es: "Gracias y de nada son como el saludo de mano de ida y vuelta: uno estira, el otro responde. Si dejas al otro con la mano estirada, quedas mal.",
          chunks: [
            {
              id: "c-thanks-a-lot",
              en: "Thanks a lot.",
              es: "Muchas gracias.",
              sounds_es: "zanks a lot",
              why_es: "\"a lot\" es el sube-volumen del \"thanks\": mismo gracias, pero más fuerte. Como cuando le subes el brazo al saludo pa' que se note más.",
              sayWhen_es: "Cuando quieres agradecer con ganas.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Thanks a little.", "Thank you lot."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-no-problem",
              en: "No problem.",
              es: "Con gusto / no hay lío.",
              sounds_es: "nou próblem",
              why_es: "Cuando te dan las gracias, esta es la que rebotas con un compañero. Es el \"tranquilo, no hay lío\" de toda la vida: le quitas peso al favor.",
              sayWhen_es: "Cuando te agradecen y respondes relajado.",
              who_es: "con un compañero",
              frame: null,
              swaps: null,
              distractors_es: ["No, thanks.", "Never mind."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-youre-welcome",
              en: "You're welcome.",
              es: "De nada.",
              sounds_es: "iúr güélcom",
              why_es: "El \"de nada\" neutro, el que le puedes decir hasta al jefe sin pena. Cuando dudes entre este y \"no problem\", con este nunca te caes.",
              sayWhen_es: "Cuando te dan las gracias, versión neutra.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Welcome, you.", "You are new here."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-same-to-you",
              en: "Same to you.",
              es: "Igualmente.",
              sounds_es: "séim tu iú",
              why_es: "Cuando te desean algo bueno (\"have a good weekend\"), en vez de repetir todo el rollo, rebotas \"same to you\" y quedas fino. Es el espejo: te deseo lo mismo.",
              sayWhen_es: "Cuando te desean algo y lo devuelves.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Same for me too.", "Some to you."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-have-a-good-weekend",
              en: "Have a good weekend.",
              es: "Buen fin de semana.",
              sounds_es: "jav a gud güíkend",
              why_es: "La frase del viernes. El día que la sueltas y te la devuelven sin pensar, ya eres del grupo: esa es la señal de que te adoptaron.",
              sayWhen_es: "El viernes, al despedirte.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Have a good week.", "Have the good weekend."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
      ],
      task: {
        id: "u4-task",
        intro_es: "Es lunes, llegas y todos están con el cafecito. Toca romper el hielo…",
        steps: [
          {
            goal_es: "Te cruzas a un compañero un lunes. Pregunta cómo estuvo su finde.",
            answerChunkId: "c-how-was-weekend",
            reaction_es: "¡Eso! Con esa ya eres parte del cafecito.",
          },
          {
            goal_es: "Te hacen un favor. Dales las gracias fuerte.",
            answerChunkId: "c-thanks-a-lot",
            reaction_es: "De una. Un gracias así nunca sobra.",
          },
          {
            goal_es: "Es viernes, te vas. Desea buen finde.",
            answerChunkId: "c-have-a-good-weekend",
            reaction_es: "Y si te lo devuelven… ya eres del grupo.",
          },
        ],
        done_es: "Ya sabes HACER SMALL TALK SIN SUDAR. ✓",
      },
    },
    {
      id: "u5-ayuda",
      order: 5,
      title_es: "Pedir ayuda y ubicarte",
      subtitle_es: "Moverte y pedir sin pena.",
      arc_es: "Ya te mueves por la oficina como en tu casa. Pedir ayuda es de vivos.",
      emoji: "🧭",
      cardTheme: "paper",
      icon: "🙋",
      survival: false,
      companionSetup_es: [
        "Ahora toca moverte por la oficina y pedir cosas sin pena.",
        "Dónde queda el baño, cómo pedir una mano, cómo pedir que te manden algo. Puro sobrevivir.",
      ],
      scenes: [
        {
          id: "u5-s1-ubicarte",
          order: 1,
          title_es: "Ubicarte e instalarte",
          scene_es: "Primer día en tu puesto. Necesitas ubicar todo y marcar lo tuyo.",
          icon: "🚻",
          setup_es: [
            "Antes que nada, ubica lo básico y marca tu puesto. Es tu territorio.",
            "Y tranquilo: acá se puede preguntar. Pedir permiso no le molesta a nadie.",
          ],
          analogy_es: "Instalarte es como llegar a un salón de clase nuevo: ubicas el baño, agarras tu puesto y ya dejas de andar perdido mirando pa' todo lado.",
          chunks: [
            /* El MISMO objeto que usa `t0-preguntas`. Definido arriba del curso
               porque lo comparten dos tramos; el id no cambió. */
            C_WHERE_IS_BATHROOM,
            {
              id: "c-this-is-my-desk",
              en: "This is my desk.",
              es: "Este es mi escritorio.",
              sounds_es: "dis is mái desk",
              why_es: "Chiquita pero tuya. \"This is my ___\" es el dedito que señala: my desk, my laptop, my badge. Marcas tu territorio sin pelear con nadie.",
              sayWhen_es: "Pa' señalar tu puesto o algo tuyo.",
              who_es: "con cualquiera (seguro)",
              frame: "This is my ___.",
              swaps: ["desk", "laptop", "badge"],
              distractors_es: ["This is your desk.", "That is a desk."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-can-i-ask",
              en: "Can I ask a question?",
              es: "¿Puedo hacer una pregunta?",
              sounds_es: "kan ái ask a kuéschon",
              why_es: "\"Can I…?\" es tu llave maestra: pides permiso sin sonar mandón. Es como tocar la puerta antes de entrar — con eso nadie se molesta.",
              sayWhen_es: "Antes de soltar una pregunta, pa' pedir permiso.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Can I make a question?", "Can I ask the answer?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
        {
          id: "u5-s2-pedir",
          order: 2,
          title_es: "Pedir una mano",
          scene_es: "Te trabas con algo y necesitas que alguien te ayude.",
          icon: "🤲",
          setup_es: [
            "Te vas a trabar, es normal el primer día. Lo bueno es saber pedir.",
            "Una mano, un archivo, un minutito: todo se pide sin pena y con \"please\".",
          ],
          analogy_es: "Pedir ayuda es como pedir el paso en la fila: no es rendirse, es lo que hace el que sabe moverse. El que se queda callado es el que se enreda.",
          chunks: [
            {
              id: "c-can-you-help-me",
              en: "Can you help me, please?",
              es: "¿Me puedes ayudar, por favor?",
              sounds_es: "kan iú jelp mi, plís",
              why_es: "El pedido de ayuda pa' todo, con el \"please\" de aceitito. Pedir ayuda no es de brutos: el que pregunta llega, el que se queda callado se enreda.",
              sayWhen_es: "Cuando te trabas y necesitas una mano.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Can I help you, please?", "Can you see me, please?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-send-it-to-me",
              en: "Can you send it to me?",
              es: "¿Me lo puedes enviar?",
              sounds_es: "kan iú send it tu mi",
              why_es: "\"send it TO me\": el \"to\" es la flechita que dice pa' quién va la cosa. Sin esa flechita, el archivo no sabe a dónde llegar.",
              sayWhen_es: "Cuando quieres que te manden un archivo.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Can you send it for me?", "Can you send me it to?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-do-you-have-a-minute",
              en: "Do you have a minute?",
              es: "¿Tienes un minuto?",
              sounds_es: "du iú jav a mínit",
              why_es: "Pides un ratito sin robártelo. Preguntas primero si puede, en vez de caerle encima: por eso casi siempre te dicen que sí.",
              sayWhen_es: "Cuando necesitas un ratito de alguien.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Do you have the time?", "Have you a minute?"],
              cognateHook_es: "\"minute\" es \"minuto\", casi la misma palabra. Esa ya la tenías.",
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
        {
          id: "u5-s3-entender",
          order: 3,
          title_es: "Entender cómo funciona todo",
          scene_es: "Todo es nuevo: la impresora, el programa, hasta dónde sentarte.",
          icon: "🧩",
          setup_es: [
            "El primer día no sabes ni prender la impresora, y es normal. Nadie nace sabiendo.",
            "Estas cuatro son pa' preguntar sin pena: cómo se usa, que te muestren, dónde te ubicas y a quién le caes.",
          ],
          analogy_es: "Tu primer día es como estrenar celular nuevo: no sabes dónde queda nada. Preguntar no es de perdido — es lo que hace que en dos días ya te muevas solo.",
          chunks: [
            {
              id: "c-how-does-this-work",
              en: "How does this work?",
              es: "¿Cómo funciona esto?",
              sounds_es: "jáu das dis guórk",
              why_es: "La que sacas frente a la impresora rara o el programa que nadie te explicó. Preguntar cómo se usa algo el primer día es como pedir el manual: nadie espera que nazcas sabiendo.",
              sayWhen_es: "Cuando no sabes usar una máquina o un programa.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["How this works?", "How does this works?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-can-you-show-me",
              en: "Can you show me?",
              es: "¿Me puedes mostrar?",
              sounds_es: "kan iú shóu mi",
              why_es: "A veces con que te lo cuenten no basta. \"Show me\" es pedir que te lo hagan ver — como decir \"hazlo tú primero y yo miro\". Más claro que mil explicaciones.",
              sayWhen_es: "Cuando quieres que te enseñen haciéndolo, no contándolo.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Can you show to me?", "Can you show me it?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-where-do-i-sit",
              en: "Where do I sit?",
              es: "¿Dónde me siento?",
              sounds_es: "güér du ái sit",
              why_es: "El primer día es como subirte a un bus lleno: no sabes cuál silla es tuya. \"Where do I ___?\" pregunta dónde te toca a ti, sin quedar parado como poste.",
              sayWhen_es: "Cuando no sabes cuál es tu lugar o puesto.",
              who_es: "con cualquiera (seguro)",
              frame: "Where do I ___?",
              swaps: ["sit", "go", "sign"],
              distractors_es: ["Where I sit?", "Where do I sit it?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-who-should-i-ask",
              en: "Who should I ask?",
              es: "¿A quién le pregunto?",
              sounds_es: "jú shud ái ask",
              why_es: "Cuando tienes una duda pero no sabes a quién preguntarle. En vez de tocar diez puertas, con esta preguntas cuál es la puerta correcta. Te ahorra vueltas.",
              sayWhen_es: "Cuando tienes una duda y no sabes quién la resuelve.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Who I should ask?", "Who should I ask to?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
        {
          id: "u5-s4-descanso",
          order: 4,
          title_es: "Permiso, la hora y el descanso",
          scene_es: "Llevas horas pegado a la silla. Necesitas un respiro y saber a qué hora es todo.",
          icon: "☕",
          setup_es: [
            "Nadie aguanta ocho horas sin parar. Pedir un descanso es normal y sano.",
            "Y pa' no andar perdido: aprende a preguntar a qué hora es cada cosa.",
          ],
          analogy_es: "Pedir un respiro es como pedir agua en un partido: no es rendirse, es lo que te deja seguir jugando bien. Y preguntar la hora te ubica, como mirar el reloj del estadio.",
          chunks: [
            {
              id: "c-can-i-take-a-break",
              en: "Can I take a break?",
              es: "¿Puedo tomar un descanso?",
              sounds_es: "kan ái téik a bréik",
              why_es: "Pedir el descanso no es de flojo, es de vivo: rindes más si paras un poquito. \"Can I…?\" pide permiso sin sonar mandón, como tocar la puerta antes de entrar.",
              sayWhen_es: "Cuando necesitas parar un rato pa' respirar.",
              who_es: "con el jefe",
              frame: null,
              swaps: null,
              distractors_es: ["Can I take break?", "Can I make a break?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-what-time-is-lunch",
              en: "What time is lunch?",
              es: "¿A qué hora es el almuerzo?",
              sounds_es: "guát táim is lonch",
              why_es: "Pa' ubicarte en el día sin andar perdido. \"What time is ___?\" es el molde pa' preguntar la hora de cualquier cosa: el almuerzo, la reunión, la llamada. Le metes lo que sea y ya.",
              sayWhen_es: "Cuando quieres saber a qué hora es algo.",
              who_es: "con cualquiera (seguro)",
              frame: "What time is ___?",
              swaps: ["lunch", "the meeting", "the call"],
              distractors_es: ["What hour is lunch?", "What time lunch is?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-ill-be-right-back",
              en: "I'll be right back.",
              es: "Ya vuelvo.",
              sounds_es: "áil bi ráit bak",
              why_es: "La que sueltas antes de pararte: avisas en vez de desaparecer, y nadie se queda esperando pensando que te fuiste. Cortita y educada.",
              sayWhen_es: "Antes de levantarte un momentito.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["I be right back.", "I'll be right come back."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
      ],
      task: {
        id: "u5-task",
        intro_es: "Primer día en tu puesto y necesitas moverte. A ver, pide sin pena…",
        steps: [
          {
            goal_es: "Te estás aguantando las ganas. Pregunta dónde queda el baño.",
            answerChunkId: "c-where-is-bathroom",
            reaction_es: "¡Eso! Esa es la primera que salva a todo el mundo.",
          },
          {
            goal_es: "Te trabaste con algo. Pide una mano.",
            answerChunkId: "c-can-you-help-me",
            reaction_es: "Perfecto. El que pregunta llega, ¿si me entiendes?",
          },
          {
            goal_es: "Necesitas que te pasen un archivo. Pide que te lo manden.",
            answerChunkId: "c-send-it-to-me",
            reaction_es: "De una. Con la flechita del \"to\" bien puesta.",
          },
          {
            goal_es: "La impresora no te obedece y nadie te explicó. Pregunta cómo funciona.",
            answerChunkId: "c-how-does-this-work",
            reaction_es: "¡Eso! Preguntar cómo se usa algo es de vivo, no de bruto.",
          },
          {
            goal_es: "Llevas horas sin parar. Pídele permiso al jefe pa' un descanso.",
            answerChunkId: "c-can-i-take-a-break",
            reaction_es: "Eso. Un respiro a tiempo y vuelves con toda.",
          },
        ],
        done_es: "Ya sabes PEDIR AYUDA Y UBICARTE. ✓",
      },
    },
    {
      id: "u6-reunion",
      order: 6,
      title_es: "En la reunión sin miedo",
      subtitle_es: "Entrar, opinar y salir vivo.",
      arc_es: "La reunión que te daba pánico. Entras con miedo y sales pudiendo.",
      emoji: "😰",
      cardTheme: "peach",
      icon: "💻",
      survival: false,
      companionSetup_es: [
        "Llegó la reunión, la que a mí me tumbó la primera semana. Pero tú vas con ventaja.",
        "Te doy con qué entrar, opinar sin pelear y salir sin morir. Tranquilo que yo te cubro.",
      ],
      scenes: [
        {
          id: "u6-s1-entrar",
          order: 1,
          title_es: "Entrar a la llamada",
          scene_es: "Se abre el Meet. Cámaras, micrófonos y esa vocecita de \"¿sí me oyen?\".",
          icon: "🎧",
          setup_es: [
            "Lo primero en una llamada es el lío técnico: si te oyen, si te cortas.",
            "Con estas dos sales del apuro sin quedar callado esperando a ver qué pasa.",
          ],
          analogy_es: "Entrar a una videollamada es como subirte a una tarima: antes de hablar, revisas que el micrófono prenda. Mejor un \"¿me oyen?\" que cinco minutos en mudo.",
          chunks: [
            {
              id: "c-can-you-hear-me",
              en: "Can you hear me?",
              es: "¿Me escuchan?",
              sounds_es: "kan iú jíar mi",
              why_es: "El salvavidas del Meet. Es lo primero que sueltas al entrar, cuando no sabes si el micrófono sirve. Mejor preguntar que hablar cinco minutos en mudo.",
              sayWhen_es: "Lo primero al entrar a una videollamada.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Can you listen me?", "Can you see me now?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-breaking-up",
              en: "Sorry, you're breaking up.",
              es: "Perdón, te estás cortando.",
              sounds_es: "sóri, iúr bréikin ap",
              why_es: "\"breaking up\" es que la voz te llega en pedacitos, cortada. Es la frase pa' cuando el internet traiciona y el otro suena como robot descompuesto.",
              sayWhen_es: "Cuando el otro se corta y no se le oye bien.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Sorry, you are breaking down.", "Sorry, I am breaking up."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
        {
          id: "u6-s2-opinar",
          order: 2,
          title_es: "Opinar sin pelear",
          scene_es: "Están decidiendo algo y te toca dar tu opinión.",
          icon: "🗣️",
          setup_es: [
            "Ahora te toca opinar: decir que sí, decir que no, pedir la palabra.",
            "El truco es opinar sin sonar patán. Acá el \"no\" se dice con guantes.",
          ],
          analogy_es: "Opinar en reunión es como manejar en hora pico: no te le atraviesas a nadie de golpe. Pides el paso, avisas pa' dónde vas, y nadie pita.",
          chunks: [
            {
              id: "c-i-agree",
              en: "I agree with you.",
              es: "Estoy de acuerdo contigo.",
              sounds_es: "ái agrí güid iú",
              why_es: "\"agree\" carga su \"with\" pegado como una sombra: estás de acuerdo CON alguien, no \"a\" alguien. Van juntos siempre, como uña y mugre.",
              sayWhen_es: "Cuando estás de acuerdo con alguien.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["I agree to you.", "I am agree with you."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-not-sure",
              en: "I'm not sure about that.",
              es: "No estoy muy seguro de eso.",
              sounds_es: "áim not shúr abáut dat",
              why_es: "El \"no\" con guantes. Decir \"I disagree\" a secas suena a patán buscando pelea; con esta opinas distinto sin dañar el ambiente.",
              sayWhen_es: "Cuando no estás de acuerdo, pero sin pelear.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["I am not sure for that.", "I am not sure about you."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-can-i-say-something",
              en: "Can I say something?",
              es: "¿Puedo decir algo?",
              sounds_es: "kan ái séi sámzin",
              why_es: "Pa' pedir el turno sin atropellar a nadie. Es como levantar la mano, pero con la voz: pides el paso y te lo dan.",
              sayWhen_es: "Pa' pedir la palabra sin interrumpir feo.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Can I say you something?", "Can I tell something?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
        {
          id: "u6-s3-acordar",
          order: 3,
          title_es: "Acordar y avanzar",
          scene_es: "Ya casi cierran. Toca acordar la hora y seguir con lo siguiente.",
          icon: "👍",
          setup_es: [
            "Para cerrar: aceptar un plan, anotar la hora y empujar pa' seguir.",
            "Frasecitas cortas que te hacen sonar como el que mueve la reunión.",
          ],
          analogy_es: "Cerrar acuerdos es como ponerle fecha a un plan con amigos: \"¿el viernes?\" \"listo\". Sin colgar la hora en algún lado, el plan se queda en el aire y no pasa nada.",
          chunks: [
            {
              id: "c-that-works-for-me",
              en: "That works for me.",
              es: "Eso me sirve.",
              sounds_es: "dat guórks for mi",
              why_es: "Pa' aceptar una hora o un plan sin repetir todo el cuento. Cortita y quedas profesional: es el \"por mí, listo\" de la oficina.",
              sayWhen_es: "Cuando aceptas una hora o un plan.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["That works to me.", "That work for me."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-meeting-at-3",
              en: "We have a meeting at 3.",
              es: "Tenemos reunión a las 3.",
              sounds_es: "güi jav a mítin at zri",
              why_es: "\"at\" + la hora es el clavo donde cuelgas el horario: at 3, at noon, at 10. Siempre el mismo clavo, solo cambias lo que cuelgas.",
              sayWhen_es: "Pa' avisar la hora de una reunión.",
              who_es: "con cualquiera (seguro)",
              frame: "We have a meeting at ___.",
              swaps: ["3", "noon", "10"],
              distractors_es: ["We have a meeting in 3.", "We have a meeting on 3."],
              cognateHook_es: "Ojo con \"meeting\": suena a \"mitin\", pero es una reunión de trabajo, no un mitin político.",
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-lets-move-on",
              en: "Let's move on.",
              es: "Sigamos con lo siguiente.",
              sounds_es: "lets muv on",
              why_es: "Cuando la reunión se queda pegada en un punto, esta es el empujoncito pa' avanzar. Como cuando la fila no camina y alguien dice \"bueno, sigamos\".",
              sayWhen_es: "Cuando la reunión se queda pegada y toca avanzar.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Let's move out.", "Let's go on."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
      ],
      task: {
        id: "u6-task",
        intro_es: "Bueno, la reunión temida. Respira: acá tienes con qué sobrevivirla…",
        steps: [
          {
            goal_es: "Entras a la llamada y no sabes si te oyen. Pregunta.",
            answerChunkId: "c-can-you-hear-me",
            reaction_es: "¡Eso! Mejor preguntar que hablar en mudo cinco minutos.",
          },
          {
            goal_es: "Alguien propone algo y te parece bien. Dile que estás de acuerdo.",
            answerChunkId: "c-i-agree",
            reaction_es: "Perfecto, con el \"with\" bien pegado. Nunca \"agree to\".",
          },
          {
            goal_es: "La reunión se quedó pegada. Empuja pa' seguir.",
            answerChunkId: "c-lets-move-on",
            reaction_es: "Eso. Ya suenas como el que maneja la reunión.",
          },
        ],
        done_es: "Ya sabes SOBREVIVIR LA REUNIÓN SIN MIEDO. ✓",
      },
    },
    {
      id: "u7-tareas",
      order: 7,
      title_es: "Tareas, quedar y cerrar la semana",
      subtitle_es: "Cumplir y despedirte como pro.",
      arc_es: "Cierra la semana. Ya no eres el nuevo asustado: ya eres del grupo.",
      emoji: "🎉",
      cardTheme: "blue",
      icon: "📋",
      survival: false,
      companionSetup_es: [
        "Última milla: te dejan tareas, mandas un correo y cierras la semana.",
        "Con estas quedas como el que cumple. Y el viernes te despides ya siendo del grupo.",
      ],
      scenes: [
        {
          id: "u7-s1-tareas",
          order: 1,
          title_es: "Tareas y tiempos",
          scene_es: "Te empiezan a caer tareas con sus fechas. Toca responder bien.",
          icon: "⏰",
          setup_es: [
            "Te van a dejar tareas y a preguntarte por tiempos. Hay que responder parado.",
            "Comprometerte, preguntar la fecha, pedir más tiempo si toca: todo sin drama.",
          ],
          analogy_es: "Responder por una tarea es como recibir un balón: o lo agarras y dices \"yo la llevo\", o lo dejas caer y quedas mal. Mejor un \"yo me encargo\" claro.",
          chunks: [
            {
              id: "c-ill-do-it-now",
              en: "I'll do it now.",
              es: "Lo hago ahora.",
              sounds_es: "áil du it náu",
              why_es: "\"I'll\" es \"yo me encargo\", dicho de una. Corta y decidida: con eso quedas como el que resuelve, no el que se hace el bobo.",
              sayWhen_es: "Cuando te encargan algo y lo asumes de una.",
              who_es: "con cualquiera (seguro)",
              frame: "I'll ___.",
              swaps: ["do it now", "check", "call"],
              distractors_es: ["I do it now.", "I'll make it now."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-send-after-lunch",
              en: "I'll send it after lunch.",
              es: "Lo mando después de almuerzo.",
              sounds_es: "áil send it áfter lanch",
              why_es: "Prometes algo cortito sin enredarte: \"lo mando después de ___\". Le cuelgas el momento (lunch, the call) y ya sabe cuándo esperarlo.",
              sayWhen_es: "Pa' prometer algo con un tiempo cortito.",
              who_es: "con cualquiera (seguro)",
              frame: "I'll send it after ___.",
              swaps: ["lunch", "the call", "the meeting"],
              distractors_es: ["I send it after lunch.", "I'll send it before lunch."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-when-deadline",
              en: "When is the deadline?",
              es: "¿Cuándo es la entrega?",
              sounds_es: "güén is de dédlain",
              why_es: "Preguntar la fecha es de pro, no de intenso. Mejor saber pa' cuándo es y organizarte, que entregar tarde y quedar mal.",
              sayWhen_es: "Pa' preguntar la fecha de entrega.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["When is the meeting?", "What is the deadline?"],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-need-more-time",
              en: "I need more time.",
              es: "Necesito más tiempo.",
              sounds_es: "ái níid mor táim",
              why_es: "Pedir más tiempo a tiempo es mil veces mejor que fallar la entrega callado. Se dice sin drama: avisar temprano es de responsable, no de flojo.",
              sayWhen_es: "Cuando ves que no alcanzas y pides tiempo.",
              who_es: "con el jefe",
              frame: null,
              swaps: null,
              distractors_es: ["I need more times.", "I want more time now."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-its-ready",
              en: "It's ready.",
              es: "Ya está listo.",
              sounds_es: "its rédi",
              why_es: "Cortita pa' avisar que terminaste. Dos palabritas que suenan a que cumples: sueltas eso y el otro respira tranquilo.",
              sayWhen_es: "Pa' avisar que terminaste algo.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["It's finish.", "I'm ready."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
        {
          id: "u7-s2-correo",
          order: 2,
          title_es: "El correo básico",
          scene_es: "Toca mandar tu primer correo. Menos susto: casi todo son fórmulas.",
          icon: "📧",
          setup_es: [
            "El correo asusta menos de lo que crees: el 80% son fórmulas armadas.",
            "Una pa' abrir, una pa' el cuerpo, una pa' cerrar. Copias, pegas y ya.",
          ],
          analogy_es: "Un correo es como armar con bloques de lego: no inventas cada pieza, encajas las que ya vienen hechas. Abres, dices lo tuyo, cierras.",
          chunks: [
            {
              id: "c-get-back-to-you",
              en: "Let me check and get back to you.",
              es: "Déjame revisar y te aviso.",
              sounds_es: "let mi chek and get bak tu iú",
              why_es: "La frase mágica pa' cuando no sabes la respuesta. En vez de inventar, dices \"déjame ver y te aviso\": ganas tiempo y quedas responsable, no perdido.",
              sayWhen_es: "Cuando no tienes la respuesta y ganas tiempo.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Let me check and come back to you.", "Let me see and get back for you."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-thanks-for-email",
              en: "Thanks for your email.",
              es: "Gracias por tu correo.",
              sounds_es: "zanks for iór ímeil",
              why_es: "Fórmula fija pa' abrir un correo. El 80% de un mail son fórmulas armadas: no las inventas, las copias y pegas como ladrillos.",
              sayWhen_es: "Pa' abrir o responder un correo.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Thanks by your email.", "Thanks for you email."],
              cognateHook_es: "\"email\" es igual que en español, esa ni la tienes que estudiar.",
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-best-regards",
              en: "Best regards.",
              es: "Saludos cordiales.",
              sounds_es: "best rigárds",
              why_es: "El cierre fijo del mail, el candado del final. Con \"Best regards\" cierras cualquier correo y quedas formal, sea al jefe o al cliente.",
              sayWhen_es: "Pa' cerrar cualquier correo.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["Better regards.", "Best regard."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
        {
          id: "u7-s3-despedir",
          order: 3,
          title_es: "Despedir la semana",
          scene_es: "Viernes en la tarde. Cierras tu primera semana en la empresa.",
          icon: "👋",
          setup_es: [
            "Llegó el viernes de tu primera semana. Toca despedirse bonito.",
            "Cierras con quien conociste y quedas pa' el lunes. Lo lograste.",
          ],
          analogy_es: "Despedir la semana es como el abrazo de salida de un paseo: cierras bonito con los que conociste y quedas invitado pa' la próxima. Eso es ya ser del grupo.",
          chunks: [
            {
              id: "c-nice-meeting-you",
              en: "It was nice meeting you.",
              es: "Fue un gusto conocerte.",
              sounds_es: "it guas náis mítin iú",
              why_es: "Es el \"nice to meet you\" pero al despedirte, mirando pa' atrás. Cuando ya conociste a alguien y te vas, cierras bonito con esta.",
              sayWhen_es: "Al despedirte de alguien que conociste esta semana.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["It is nice meeting you.", "It was nice met you."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: "c-see-you-monday",
              en: "See you on Monday.",
              es: "Nos vemos el lunes.",
              sounds_es: "síi iú on mándei",
              why_es: "El chao del viernes. Misma fórmula \"See you\" + cuándo, pero con el lunes colgado: te despides sabiendo que la próxima es después del finde.",
              sayWhen_es: "El viernes, despidiéndote hasta el lunes.",
              who_es: "con cualquiera (seguro)",
              frame: null,
              swaps: null,
              distractors_es: ["See you in Monday.", "See you on Sunday."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
      ],
      task: {
        id: "u7-task",
        intro_es: "Última milla: te dejan una tarea y toca cerrar la semana bien. Vamos…",
        steps: [
          {
            goal_es: "El jefe te deja algo urgente. Dile que lo haces ya.",
            answerChunkId: "c-ill-do-it-now",
            reaction_es: "¡Eso! Quedaste como el que resuelve.",
          },
          {
            goal_es: "No sabes la respuesta todavía. Di que revisas y avisas.",
            answerChunkId: "c-get-back-to-you",
            reaction_es: "Perfecto. Ganaste tiempo sin quedar perdido.",
          },
          {
            goal_es: "Es viernes y conociste gente nueva. Despide la semana.",
            answerChunkId: "c-see-you-monday",
            reaction_es: "Sobreviviste tu primera semana. En serio. Ya eres del grupo.",
          },
        ],
        done_es: "Ya sabes CERRAR LA SEMANA COMO UN PRO. ✓",
      },
    },
  ],
};
