/* Icono de línea (lucide) por término — reemplaza a los emojis de sistema en la
   tarjeta de significado (pedido de Gus: iconos de línea, no emojis, para que la
   UI se lea premium y coherente con el resto de la iconografía monocroma).

   El mapa vive aquí y NO en el mazo (deck.ts) a propósito: el campo `emoji` del
   SlangTerm se conserva (lo usa el modo `muro`, sin rutear), y el render de la
   vista Pélala usa este mapa por id. Un término sin entrada cae al fallback. */

import type { LucideIcon } from 'lucide-react';
import {
  Angry,
  Armchair,
  Ban,
  Blocks,
  CalendarHeart,
  CalendarX,
  CloudSun,
  Coffee,
  Coins,
  Droplets,
  Dumbbell,
  DoorOpen,
  EarOff,
  Flag,
  Ghost,
  Hand,
  Handshake,
  Lightbulb,
  MessageCircle,
  MessagesSquare,
  Milk,
  ClipboardCheck,
  Moon,
  Plane,
  PhoneCall,
  Puzzle,
  Rainbow,
  Repeat,
  Rocket,
  RotateCcw,
  Route,
  Send,
  Shuffle,
  Smartphone,
  Sparkles,
  Target,
  TrendingUp,
  Unlock,
  UserPlus,
  Users,
  VolumeX,
  Wallet,
  Waves,
  Wind,
  // Lote 3 (categorías oficina/crypto/aleatoria)
  Anchor,
  ArrowDownToLine,
  BadgeDollarSign,
  BedDouble,
  Bell,
  BookOpen,
  Cake,
  CalendarPlus,
  Cat,
  CircleAlert,
  Cloud,
  CloudRain,
  Drama,
  Fence,
  Fish,
  Flame,
  Gem,
  Gift,
  Hammer,
  HandCoins,
  Megaphone,
  MoonStar,
  PackageOpen,
  PartyPopper,
  Play,
  Scale,
  ScrollText,
  Search,
  Skull,
  Stamp,
  Star,
  Sunrise,
  Sunset,
  Thermometer,
  Timer,
  TriangleAlert,
  Zap,
} from 'lucide-react';

export const ICONO_TERMINO: Record<string, LucideIcon> = {
  'wind-up': Moon,
  'pull-off': Target,
  'run-into': Users,
  ghost: Ghost,
  'show-up': DoorOpen,
  'give-up': Flag,
  'chill-out': Wind,
  broke: Wallet,
  'hang-out': Armchair,
  'figure-out': Puzzle,
  flex: Dumbbell,
  'catch-up': Coffee,
  'work-out': Route,
  'look-forward-to': CalendarHeart,
  'come-up-with': Lightbulb,
  'get-along': Handshake,
  'turn-down': Ban,
  'put-up-with': EarOff,
  'run-out-of': Milk,
  'bring-up': MessageCircle,
  'call-off': CalendarX,
  'hit-up': Smartphone,
  'spill-the-tea': MessagesSquare,
  lowkey: VolumeX,
  swamped: Waves,
  salty: Angry,
  'wrap-up': Sparkles,
  // Lote 2
  'pay-off': Coins,
  'break-out-of': Unlock,
  'snap-out-of': CloudSun,
  'shake-off': Droplets,
  'get-over': Rainbow,
  'get-a-grip': Hand,
  'daily-grind': Repeat,
  'switch-up': Shuffle,
  'pull-yourself-together': Blocks,
  'up-in-the-air': Plane,
  // Oficina
  'touch-base': Handshake,
  'circle-back': RotateCcw,
  'follow-up': Send,
  'reach-out': PhoneCall,
  'loop-in': UserPlus,
  'run-by': ClipboardCheck,
  'ramp-up': TrendingUp,
  'roll-out': Rocket,
  // Oficina (lote 3)
  'on-the-same-page': BookOpen,
  'get-the-ball-rolling': Play,
  'think-outside-the-box': PackageOpen,
  'hammer-out': Hammer,
  'pencil-in': CalendarPlus,
  'weigh-in': Scale,
  'sign-off': Stamp,
  // Crypto
  hodl: HandCoins,
  'to-the-moon': MoonStar,
  'rug-pull': TriangleAlert,
  'diamond-hands': Gem,
  'paper-hands': ScrollText,
  fomo: Timer,
  fud: CloudRain,
  'ape-in': ArrowDownToLine,
  whale: Fish,
  degen: Flame,
  shill: Megaphone,
  dyor: Search,
  wagmi: PartyPopper,
  rekt: Skull,
  gm: Sunrise,
  // Aleatoria
  'piece-of-cake': Cake,
  'hit-the-sack': BedDouble,
  'under-the-weather': Thermometer,
  'cost-an-arm-and-a-leg': BadgeDollarSign,
  'once-in-a-blue-moon': Star,
  'break-a-leg': Drama,
  'call-it-a-day': Sunset,
  'ring-a-bell': Bell,
  'on-cloud-nine': Cloud,
  'bite-the-bullet': Zap,
  'hang-in-there': Anchor,
  'the-last-straw': CircleAlert,
  'blessing-in-disguise': Gift,
  'on-the-fence': Fence,
  'let-the-cat-out-of-the-bag': Cat,
};

/** Fallback si un término no está en el mapa. */
export const ICONO_FALLBACK: LucideIcon = Sparkles;
