/* Mazo curado de Pélala / El Muro — jerga y phrasal verbs de inglés real.
   Un solo término alimenta los dos modos:
   · El Muro  → muestra term + contexto + gloss; el usuario lo pela cuando ya se lo sabe.
   · Pélala   → muestra la imagen (o el contexto con el término en blanco); el usuario
                dice/escribe la respuesta y se valida contra `accept`.

   `accept` es el chequeo local rápido; el juez real (api/chat.js) tolera variantes.
   `image` queda como pack curado pre-generado (fase de contenido posterior); por ahora
   `emoji` da un placeholder demostrable y Pélala arranca en variante "contexto en blanco". */

export type SlangKind = 'phrasal' | 'slang' | 'idiom';

/** Categorías de exploración de Pélala (el botón «explorar» las abre). */
export type CategoriaId = 'dia-a-dia' | 'oficina' | 'crypto' | 'aleatoria';

/** Un significado de un término polisémico (ver `senses`). */
export type SlangSense = {
  /** El significado, en español latino neutro. */
  gloss_es: string;
  /** Ejemplo natural en inglés para ESTE significado. */
  example_en: string;
  /** Traducción del ejemplo. */
  example_es: string;
};

export type SlangTerm = {
  id: string;
  term: string;
  kind: SlangKind;
  /** Categoría de exploración; SIN valor = 'dia-a-dia' (calle/vida). */
  cat?: CategoriaId;
  /** Frase natural que usa el término (para El Muro y para el fill-in-the-blank de Pélala). */
  context_en: string;
  /** El término tal como aparece en context_en, para poder blanquearlo. */
  target: string;
  /** Glosa en español latino neutro. */
  gloss_es: string;
  /** Respuestas aceptadas (base + flexiones + con pronombre). */
  accept: string[];
  /** Placeholder inmediato mientras no exista el pack de imágenes. */
  emoji: string;
  /** Prompt para generar la imagen de acción del pack curado (fase posterior). */
  imagePrompt: string;
  /** Términos con VARIOS significados (p. ej. "pay off": vale la pena / saldar una
      deuda / sobornar): un solo sticker, pero la tarjeta de significado los explica
      todos. Si está presente, el render revelado lo usa en vez de gloss_es solo. */
  senses?: SlangSense[];
};

export const DECK: SlangTerm[] = [
  {
    id: 'wind-up',
    term: 'wind up',
    kind: 'phrasal',
    context_en: 'We wound up talking until 3 a.m.',
    target: 'wound up',
    gloss_es: 'terminar/acabar haciendo algo (sin planearlo)',
    accept: ['wind up', 'wound up', 'winds up', 'winding up', 'wind up doing', 'wound up doing'],
    emoji: '🌀',
    imagePrompt:
      'flat illustration of a winding spiral swirl leading into a speech bubble, crescent moon and stars for late night, minimal',
  },
  {
    id: 'pull-off',
    term: 'pull off',
    kind: 'phrasal',
    context_en: 'She pulled off the deal nobody believed in.',
    target: 'pulled off',
    gloss_es: 'lograr algo difícil contra todo pronóstico',
    accept: ['pull off', 'pulled off', 'pull it off', 'pulled it off'],
    emoji: '🎯',
    imagePrompt:
      'flat illustration of a person celebrating after closing an impossible deal, confetti, minimal',
  },
  {
    id: 'run-into',
    term: 'run into',
    kind: 'phrasal',
    context_en: 'I ran into my ex at the mall.',
    target: 'ran into',
    gloss_es: 'toparse con alguien por casualidad',
    accept: ['run into', 'ran into', 'bump into', 'bumped into'],
    emoji: '😳',
    imagePrompt:
      'flat illustration of two people bumping into each other surprised at a shopping mall, minimal',
  },
  {
    id: 'ghost',
    term: 'ghost',
    kind: 'slang',
    context_en: 'He ghosted me after two dates.',
    target: 'ghosted',
    gloss_es: 'desaparecer / cortar el contacto sin dar explicación',
    accept: ['ghost', 'ghosted', 'ghost me', 'ghosted me'],
    emoji: '👻',
    imagePrompt:
      'flat illustration of a person staring at a phone with no reply, faded ghost silhouette leaving, minimal',
  },
  {
    id: 'show-up',
    term: 'show up',
    kind: 'phrasal',
    context_en: 'Only three people showed up to the party.',
    target: 'showed up',
    gloss_es: 'aparecer / presentarse a un lugar',
    accept: ['show up', 'showed up', 'shows up'],
    emoji: '🚪',
    imagePrompt:
      'flat illustration of a nearly empty party with three guests arriving, minimal',
  },
  {
    id: 'give-up',
    term: 'give up',
    kind: 'phrasal',
    context_en: "Don't give up now, you're almost there.",
    target: 'give up',
    gloss_es: 'rendirse / dejar de intentar',
    accept: ['give up', 'gave up', 'giving up', 'give it up'],
    emoji: '🏳️',
    imagePrompt:
      'flat illustration of a runner refusing to quit near the finish line, minimal',
  },
  {
    id: 'chill-out',
    term: 'chill out',
    kind: 'phrasal',
    context_en: "Chill out, it's not a big deal.",
    target: 'chill out',
    gloss_es: 'relajarse / calmarse',
    accept: ['chill out', 'chilled out', 'chill'],
    emoji: '😎',
    imagePrompt:
      'flat illustration of a relaxed person lying back calm and cool, minimal',
  },
  {
    id: 'broke',
    term: 'broke',
    kind: 'slang',
    context_en: "I can't go out tonight, I'm broke.",
    target: 'broke',
    gloss_es: 'sin plata / quebrado',
    accept: ['broke', "i'm broke", 'im broke', 'be broke'],
    emoji: '💸',
    imagePrompt:
      'flat illustration of a person turning an empty wallet upside down, minimal',
  },
  {
    id: 'hang-out',
    term: 'hang out',
    kind: 'phrasal',
    context_en: 'We hung out at the park all afternoon.',
    target: 'hung out',
    gloss_es: 'pasar el rato con alguien',
    accept: ['hang out', 'hung out', 'hangs out', 'hanging out'],
    emoji: '🧃',
    imagePrompt:
      'flat illustration of friends relaxing together on the grass at a park, minimal',
  },
  {
    id: 'figure-out',
    term: 'figure out',
    kind: 'phrasal',
    context_en: "I can't figure out this problem.",
    target: 'figure out',
    gloss_es: 'descifrar / resolver algo',
    accept: ['figure out', 'figured out', 'figure it out', 'figuring out'],
    emoji: '🧩',
    imagePrompt:
      'flat illustration of a person having an aha moment solving a puzzle, lightbulb, minimal',
  },
  {
    id: 'flex',
    term: 'flex',
    kind: 'slang',
    context_en: "He's always flexing his new car.",
    target: 'flexing',
    gloss_es: 'presumir / alardear',
    accept: ['flex', 'flexing', 'flexed'],
    emoji: '💪',
    imagePrompt:
      'flat illustration of a person showing off a shiny new car proudly, minimal',
  },
  {
    id: 'catch-up',
    term: 'catch up',
    kind: 'phrasal',
    context_en: "Let's catch up over coffee this weekend.",
    target: 'catch up',
    gloss_es: 'ponerse al día con alguien',
    accept: ['catch up', 'caught up', 'catching up', 'catch up with'],
    emoji: '☕',
    imagePrompt: 'flat illustration of two friends chatting over coffee catching up, minimal',
  },
  {
    id: 'work-out',
    term: 'work out',
    kind: 'phrasal',
    context_en: "Don't worry, everything will work out fine.",
    target: 'work out',
    gloss_es: 'resolverse / salir bien',
    accept: ['work out', 'worked out', 'works out', 'working out'],
    emoji: '🤞',
    imagePrompt: 'flat illustration of a tangled path straightening into a clear road, minimal',
  },
  {
    id: 'look-forward-to',
    term: 'look forward to',
    kind: 'phrasal',
    context_en: "I'm looking forward to the trip.",
    target: 'looking forward to',
    gloss_es: 'tener muchas ganas de algo',
    accept: ['look forward to', 'looking forward to', 'looked forward to'],
    emoji: '🤩',
    imagePrompt: 'flat illustration of a person excitedly counting days on a calendar, minimal',
  },
  {
    id: 'come-up-with',
    term: 'come up with',
    kind: 'phrasal',
    context_en: 'She came up with a brilliant idea.',
    target: 'came up with',
    gloss_es: 'idear / inventar algo',
    accept: ['come up with', 'came up with', 'coming up with'],
    emoji: '💡',
    imagePrompt: 'flat illustration of a person with a lightbulb popping above their head, minimal',
  },
  {
    id: 'get-along',
    term: 'get along',
    kind: 'phrasal',
    context_en: 'I get along with my coworkers.',
    target: 'get along',
    gloss_es: 'llevarse bien con alguien',
    accept: ['get along', 'got along', 'getting along', 'get along with'],
    emoji: '🤝',
    imagePrompt: 'flat illustration of two coworkers laughing together friendly, minimal',
  },
  {
    id: 'turn-down',
    term: 'turn down',
    kind: 'phrasal',
    context_en: 'He turned down the job offer.',
    target: 'turned down',
    gloss_es: 'rechazar una oferta o propuesta',
    accept: ['turn down', 'turned down', 'turning down', 'turn it down'],
    emoji: '🙅',
    imagePrompt: 'flat illustration of a person politely declining a contract, minimal',
  },
  {
    id: 'put-up-with',
    term: 'put up with',
    kind: 'phrasal',
    context_en: "I can't put up with the noise anymore.",
    target: 'put up with',
    gloss_es: 'aguantar / soportar algo molesto',
    accept: ['put up with', 'putting up with', 'put up with it'],
    emoji: '😤',
    imagePrompt: 'flat illustration of a person covering their ears from loud noise, minimal',
  },
  {
    id: 'run-out-of',
    term: 'run out of',
    kind: 'phrasal',
    context_en: 'We ran out of milk this morning.',
    target: 'ran out of',
    gloss_es: 'quedarse sin algo',
    accept: ['run out of', 'ran out of', 'running out of', 'run out'],
    emoji: '🥛',
    imagePrompt: 'flat illustration of an empty fridge with a lone empty milk carton, minimal',
  },
  {
    id: 'bring-up',
    term: 'bring up',
    kind: 'phrasal',
    context_en: "Don't bring up politics at dinner.",
    target: 'bring up',
    gloss_es: 'sacar un tema / mencionar algo',
    accept: ['bring up', 'brought up', 'bringing up', 'bring it up'],
    emoji: '💬',
    imagePrompt: 'flat illustration of a speech bubble raised at a dinner table, minimal',
  },
  {
    id: 'call-off',
    term: 'call off',
    kind: 'phrasal',
    context_en: 'They called off the wedding.',
    target: 'called off',
    gloss_es: 'cancelar algo ya planeado',
    accept: ['call off', 'called off', 'calling off', 'call it off'],
    emoji: '🚫',
    imagePrompt: 'flat illustration of a crossed-out calendar event, minimal',
  },
  {
    id: 'hit-up',
    term: 'hit up',
    kind: 'slang',
    context_en: 'Hit me up when you land.',
    target: 'Hit me up',
    gloss_es: 'escríbeme / contáctame',
    accept: ['hit up', 'hit me up', 'hit you up', 'hit them up'],
    emoji: '📲',
    imagePrompt: 'flat illustration of a phone buzzing with a new message, minimal',
  },
  {
    id: 'spill-the-tea',
    term: 'spill the tea',
    kind: 'slang',
    context_en: 'Okay, spill the tea — what happened?',
    target: 'spill the tea',
    gloss_es: 'suelta el chisme / cuéntalo todo',
    accept: ['spill the tea', 'spilled the tea', 'spill the beans'],
    emoji: '🍵',
    imagePrompt: 'flat illustration of a teacup with gossip bubbles rising, minimal',
  },
  {
    id: 'lowkey',
    term: 'lowkey',
    kind: 'slang',
    context_en: "I'm lowkey obsessed with this song.",
    target: 'lowkey',
    gloss_es: 'medio / en secreto (un poquito)',
    accept: ['lowkey', 'low key', 'low-key'],
    emoji: '🤫',
    imagePrompt: 'flat illustration of a person secretly enjoying music with headphones, minimal',
  },
  {
    id: 'swamped',
    term: 'swamped',
    kind: 'slang',
    context_en: "I'm swamped with work this week.",
    target: 'swamped',
    gloss_es: 'hasta el cuello de trabajo',
    accept: ['swamped', 'be swamped', "i'm swamped", 'im swamped'],
    emoji: '🌊',
    imagePrompt: 'flat illustration of a person under a wave of paperwork, minimal',
  },
  {
    id: 'salty',
    term: 'salty',
    kind: 'slang',
    context_en: "He's still salty about losing the game.",
    target: 'salty',
    gloss_es: 'resentido / picado / amargado',
    accept: ['salty', 'be salty', 'so salty'],
    emoji: '🧂',
    imagePrompt: 'flat illustration of a grumpy person with a salt shaker mood, minimal',
  },
  {
    id: 'wrap-up',
    term: 'wrap up',
    kind: 'phrasal',
    context_en: "Let's wrap up the meeting.",
    target: 'wrap up',
    gloss_es: 'cerrar / terminar algo',
    accept: ['wrap up', 'wrapped up', 'wrapping up', 'wrap it up'],
    emoji: '🎁',
    imagePrompt: 'flat illustration of hands tying a bow to close a wrapped box, minimal',
  },
  /* ── Lote 2 (2026-08-19): términos sacados de cuentas de inglés en Instagram
     (vocabulary_sailingo, teacheromizz, johnplusenglish…) y con sticker ilustrado
     propio en STICKER_IMG. "pay off" trae `senses`: un solo sticker, tres usos. ── */
  {
    id: 'pay-off',
    term: 'pay off',
    kind: 'phrasal',
    context_en: 'All those late nights finally paid off.',
    target: 'paid off',
    gloss_es: 'dar frutos / valer la pena el esfuerzo',
    accept: ['pay off', 'paid off', 'pays off', 'paying off', 'pay it off', 'paid it off'],
    emoji: '💰',
    imagePrompt:
      'flat sticker of a green sprout growing out of a jar of gold coins with a sparkling star, effort paying off, minimal',
    senses: [
      {
        gloss_es: 'Valer la pena / dar frutos (un esfuerzo).',
        example_en: 'All those late nights finally paid off.',
        example_es: 'Todas esas trasnochadas al final valieron la pena.',
      },
      {
        gloss_es: 'Terminar de pagar una deuda por completo.',
        example_en: 'I finally paid off my credit card.',
        example_es: 'Por fin terminé de pagar la tarjeta de crédito.',
      },
      {
        gloss_es: 'Sobornar a alguien (informal).',
        example_en: 'They paid off the inspector to stay quiet.',
        example_es: 'Sobornaron al inspector para que se quedara callado.',
      },
    ],
  },
  {
    id: 'break-out-of',
    term: 'break out of',
    kind: 'phrasal',
    context_en: 'I want to break out of this boring routine.',
    target: 'break out of',
    gloss_es: 'escapar de algo; salir de golpe de una situación o rutina',
    accept: ['break out of', 'broke out of', 'breaking out of', 'break out'],
    emoji: '🔓',
    imagePrompt:
      'flat sticker of a happy character leaping out through bent-open prison bars, breaking free, minimal',
  },
  {
    id: 'snap-out-of',
    term: 'snap out of',
    kind: 'phrasal',
    context_en: 'Snap out of it — we can fix this.',
    target: 'Snap out of',
    gloss_es: 'espabilar; salir de golpe de un bajón, tristeza o distracción',
    accept: ['snap out of', 'snap out of it', 'snapped out of', 'snaps out of'],
    emoji: '🫰',
    imagePrompt:
      'flat sticker of a character snapping fingers as a grey gloom cloud dissolves, brightening up, minimal',
  },
  {
    id: 'shake-off',
    term: 'shake off',
    kind: 'phrasal',
    context_en: "I can't shake off this cold.",
    target: 'shake off',
    gloss_es: 'quitarse de encima algo o a alguien molesto',
    accept: ['shake off', 'shook off', 'shakes off', 'shaking off', 'shake it off'],
    emoji: '💦',
    imagePrompt:
      'flat sticker of a puppy-like character shaking off water droplets and a clingy burr, motion lines, minimal',
  },
  {
    id: 'get-over',
    term: 'get over',
    kind: 'phrasal',
    context_en: 'It took her months to get over the breakup.',
    target: 'get over',
    gloss_es: 'superar algo (una enfermedad, una ruptura, un mal momento)',
    accept: ['get over', 'got over', 'gets over', 'getting over', 'get over it'],
    emoji: '🌈',
    imagePrompt:
      'flat sticker of a character stepping over a hill toward a rising sun, moving past an obstacle, minimal',
  },
  {
    id: 'get-a-grip',
    term: 'get a grip',
    kind: 'idiom',
    context_en: "Get a grip — it's not the end of the world.",
    target: 'Get a grip',
    gloss_es: 'controlarse y recuperar la calma',
    accept: ['get a grip', 'got a grip', 'get a grip on', 'getting a grip'],
    emoji: '✊',
    imagePrompt:
      'flat sticker of two hands firmly steadying a wobbling steering wheel, calm control, minimal',
  },
  {
    id: 'daily-grind',
    term: 'the daily grind',
    kind: 'idiom',
    context_en: 'Coffee helps me get through the daily grind.',
    target: 'daily grind',
    gloss_es: 'la rutina diaria de trabajo o estudio, monótona y agotadora',
    accept: ['daily grind', 'the daily grind', 'back to the grind'],
    emoji: '☕',
    imagePrompt:
      'flat sticker of a tired character walking a hamster wheel holding coffee, a big gear turning, minimal',
  },
  {
    id: 'switch-up',
    term: 'switch up',
    kind: 'phrasal',
    context_en: "Let's switch up the routine this week.",
    target: 'switch up',
    gloss_es: 'cambiar algo, darle un giro (a la rutina, el plan, el estilo)',
    accept: ['switch up', 'switched up', 'switching up', 'switch it up'],
    emoji: '🔀',
    imagePrompt:
      'flat sticker of a character flipping a chunky toggle switch with two swapping arrows, fresh change, minimal',
  },
  {
    id: 'pull-yourself-together',
    term: 'pull yourself together',
    kind: 'idiom',
    context_en: 'Pull yourself together and tell me what happened.',
    target: 'Pull yourself together',
    gloss_es: 'recomponerse: calmarse y recuperar el control',
    accept: ['pull yourself together', 'pull myself together', 'pulled himself together', 'pull it together'],
    emoji: '🧩',
    imagePrompt:
      'flat sticker of a character clicking floating puzzle-piece parts of itself back into place, composed, minimal',
  },
  {
    id: 'up-in-the-air',
    term: 'up in the air',
    kind: 'idiom',
    context_en: 'The wedding date is still up in the air.',
    target: 'up in the air',
    gloss_es: 'en el aire: incierto, sin decidir, sin saberse aún qué pasará',
    accept: ['up in the air', 'still up in the air', 'be up in the air'],
    emoji: '🎈',
    imagePrompt:
      'flat sticker of a character shrugging with a paper plane, question mark and balloon floating around, uncertainty, minimal',
  },
  /* ── Categoría OFICINA (2026-08-19): el inglés de reuniones, correos y trabajo.
     `cat: 'oficina'` los separa del feed por defecto; el botón «explorar» cambia. ── */
  {
    id: 'touch-base',
    term: 'touch base',
    kind: 'idiom',
    cat: 'oficina',
    context_en: "Let's touch base next week about the plan.",
    target: 'touch base',
    gloss_es: 'hacer un contacto rápido para ponerse al día',
    accept: ['touch base', 'touched base', 'touch base with', 'touching base'],
    emoji: '🤝',
    imagePrompt: 'flat sticker of two fists bumping in a quick friendly check-in, minimal',
  },
  {
    id: 'circle-back',
    term: 'circle back',
    kind: 'phrasal',
    cat: 'oficina',
    context_en: "Let's circle back on this tomorrow.",
    target: 'circle back',
    gloss_es: 'retomar un tema más adelante',
    accept: ['circle back', 'circled back', 'circle back to', 'circle back on', 'circling back'],
    emoji: '🔄',
    imagePrompt: 'flat sticker of a looping return arrow curving back to a chat bubble, minimal',
  },
  {
    id: 'follow-up',
    term: 'follow up',
    kind: 'phrasal',
    cat: 'oficina',
    context_en: "I'll follow up with an email after the call.",
    target: 'follow up',
    gloss_es: 'dar seguimiento a algo o a alguien',
    accept: ['follow up', 'followed up', 'following up', 'follow up on', 'follow up with'],
    emoji: '📩',
    imagePrompt: 'flat sticker of a character sending an envelope with a checkmark and a clock, minimal',
  },
  {
    id: 'reach-out',
    term: 'reach out',
    kind: 'phrasal',
    cat: 'oficina',
    context_en: 'Reach out if you need anything.',
    target: 'Reach out',
    gloss_es: 'contactar a alguien (para pedir o ofrecer ayuda)',
    accept: ['reach out', 'reached out', 'reaching out', 'reach out to'],
    emoji: '🙋',
    imagePrompt: 'flat sticker of a character extending a hand toward a chat bubble, reaching out, minimal',
  },
  {
    id: 'loop-in',
    term: 'loop in',
    kind: 'phrasal',
    cat: 'oficina',
    context_en: 'Let me loop in the design team on this.',
    target: 'loop in',
    gloss_es: 'incluir a alguien en un tema o conversación',
    accept: ['loop in', 'looped in', 'looping in', 'loop me in'],
    emoji: '➰',
    imagePrompt: 'flat sticker of a rope loop gathering two colleagues into the group, minimal',
  },
  {
    id: 'run-by',
    term: 'run by',
    kind: 'phrasal',
    cat: 'oficina',
    context_en: 'Can I run this by you before I send it?',
    target: 'run this by',
    gloss_es: 'consultar algo con alguien para conocer su opinión',
    accept: ['run by', 'run it by', 'run this by', 'ran by', 'run that by'],
    emoji: '💭',
    imagePrompt: 'flat sticker of a character showing a clipboard idea to another for a quick opinion, minimal',
  },
  {
    id: 'ramp-up',
    term: 'ramp up',
    kind: 'phrasal',
    cat: 'oficina',
    context_en: 'We need to ramp up production this quarter.',
    target: 'ramp up',
    gloss_es: 'aumentar o intensificar (producción, esfuerzo, ritmo)',
    accept: ['ramp up', 'ramped up', 'ramping up'],
    emoji: '📈',
    imagePrompt: 'flat sticker of a character running up a rising arrow chart, increasing, minimal',
  },
  {
    id: 'roll-out',
    term: 'roll out',
    kind: 'phrasal',
    cat: 'oficina',
    context_en: "We're rolling out the new feature next week.",
    target: 'rolling out',
    gloss_es: 'lanzar o desplegar algo nuevo (un producto, una función)',
    accept: ['roll out', 'rolled out', 'rolling out'],
    emoji: '🚀',
    imagePrompt: 'flat sticker of a character unrolling a red carpet while a rocket lifts off, launching, minimal',
  },
  {
    id: 'on-the-same-page',
    term: 'on the same page',
    kind: 'idiom',
    cat: 'oficina',
    context_en: 'Let\'s make sure we\'re on the same page.',
    target: 'on the same page',
    gloss_es: 'estar de acuerdo o alineados',
    accept: ['on the same page', 'same page'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'get-the-ball-rolling',
    term: 'get the ball rolling',
    kind: 'idiom',
    cat: 'oficina',
    context_en: 'Let\'s get the ball rolling on the project.',
    target: 'get the ball rolling',
    gloss_es: 'poner algo en marcha, arrancar',
    accept: ['get the ball rolling', 'ball rolling', 'got the ball rolling'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'think-outside-the-box',
    term: 'think outside the box',
    kind: 'idiom',
    cat: 'oficina',
    context_en: 'We need to think outside the box here.',
    target: 'think outside the box',
    gloss_es: 'pensar de forma creativa u original',
    accept: ['think outside the box', 'outside the box', 'thinking outside the box'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'hammer-out',
    term: 'hammer out',
    kind: 'phrasal',
    cat: 'oficina',
    context_en: 'We hammered out the details in the meeting.',
    target: 'hammered out',
    gloss_es: 'negociar o resolver los detalles a fondo',
    accept: ['hammer out', 'hammered out', 'hammering out'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'pencil-in',
    term: 'pencil in',
    kind: 'phrasal',
    cat: 'oficina',
    context_en: 'Let\'s pencil in Friday for the demo.',
    target: 'pencil in',
    gloss_es: 'agendar algo de forma tentativa',
    accept: ['pencil in', 'penciled in', 'pencil you in'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'weigh-in',
    term: 'weigh in',
    kind: 'phrasal',
    cat: 'oficina',
    context_en: 'Can you weigh in on this decision?',
    target: 'weigh in',
    gloss_es: 'dar tu opinión sobre un tema',
    accept: ['weigh in', 'weighed in', 'weighing in', 'weigh in on'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'sign-off',
    term: 'sign off',
    kind: 'phrasal',
    cat: 'oficina',
    context_en: 'The boss signed off on the budget.',
    target: 'signed off',
    gloss_es: 'aprobar algo oficialmente',
    accept: ['sign off', 'signed off', 'sign off on', 'signing off'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'hodl',
    term: 'HODL',
    kind: 'slang',
    cat: 'crypto',
    context_en: 'I\'m just going to HODL through the dip.',
    target: 'HODL',
    gloss_es: 'aguantar la inversión sin vender, aunque baje',
    accept: ['hodl', 'hodling', 'hodled', 'hold'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'to-the-moon',
    term: 'to the moon',
    kind: 'slang',
    cat: 'crypto',
    context_en: 'This coin is going to the moon!',
    target: 'to the moon',
    gloss_es: 'cuando el precio se dispara muy alto',
    accept: ['to the moon', 'moon', 'mooning'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'rug-pull',
    term: 'rug pull',
    kind: 'slang',
    cat: 'crypto',
    context_en: 'The whole project was a rug pull.',
    target: 'rug pull',
    gloss_es: 'estafa: los creadores desaparecen con el dinero',
    accept: ['rug pull', 'rugged', 'rug pulled', 'rug'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'diamond-hands',
    term: 'diamond hands',
    kind: 'slang',
    cat: 'crypto',
    context_en: 'Diamond hands — we don\'t sell.',
    target: 'diamond hands',
    gloss_es: 'aguantar la inversión pese a la volatilidad',
    accept: ['diamond hands', 'diamond handed'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'paper-hands',
    term: 'paper hands',
    kind: 'slang',
    cat: 'crypto',
    context_en: 'He has paper hands — he sold at the first dip.',
    target: 'paper hands',
    gloss_es: 'vender demasiado pronto por miedo',
    accept: ['paper hands', 'paper handed'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'fomo',
    term: 'FOMO',
    kind: 'slang',
    cat: 'crypto',
    context_en: 'I bought out of pure FOMO.',
    target: 'FOMO',
    gloss_es: 'miedo a quedarte afuera y perderte la subida',
    accept: ['fomo', 'fomoing', 'fomo in'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'fud',
    term: 'FUD',
    kind: 'slang',
    cat: 'crypto',
    context_en: 'Ignore the FUD and do your research.',
    target: 'FUD',
    gloss_es: 'miedo, incertidumbre y duda (noticias negativas)',
    accept: ['fud', 'fudding', 'spreading fud'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'ape-in',
    term: 'ape in',
    kind: 'slang',
    cat: 'crypto',
    context_en: 'I aped in without reading anything.',
    target: 'aped in',
    gloss_es: 'invertir de golpe e impulsivamente',
    accept: ['ape in', 'aped in', 'aping in', 'ape'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'whale',
    term: 'whale',
    kind: 'slang',
    cat: 'crypto',
    context_en: 'A whale just moved a million dollars.',
    target: 'whale',
    gloss_es: 'alguien con una cantidad enorme de cripto',
    accept: ['whale', 'whales'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'degen',
    term: 'degen',
    kind: 'slang',
    cat: 'crypto',
    context_en: 'That\'s such a degen move.',
    target: 'degen',
    gloss_es: 'trader temerario que apuesta sin pensar',
    accept: ['degen', 'degens'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'shill',
    term: 'shill',
    kind: 'slang',
    cat: 'crypto',
    context_en: 'Stop shilling that coin.',
    target: 'shilling',
    gloss_es: 'promocionar una moneda, casi siempre por interés propio',
    accept: ['shill', 'shilling', 'shilled'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'dyor',
    term: 'DYOR',
    kind: 'slang',
    cat: 'crypto',
    context_en: 'Not financial advice — DYOR.',
    target: 'DYOR',
    gloss_es: 'haz tu propia investigación',
    accept: ['dyor'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'wagmi',
    term: 'WAGMI',
    kind: 'slang',
    cat: 'crypto',
    context_en: 'Stay strong — WAGMI!',
    target: 'WAGMI',
    gloss_es: 'vamos a lograrlo todos (optimismo de la comunidad)',
    accept: ['wagmi'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'rekt',
    term: 'rekt',
    kind: 'slang',
    cat: 'crypto',
    context_en: 'I got rekt on that trade.',
    target: 'rekt',
    gloss_es: 'quedar destrozado por una pérdida enorme',
    accept: ['rekt', 'get rekt', 'got rekt'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'gm',
    term: 'gm',
    kind: 'slang',
    cat: 'crypto',
    context_en: 'gm — ready to build today?',
    target: 'gm',
    gloss_es: '\'good morning\', el saludo de la comunidad cripto',
    accept: ['gm', 'gm gm'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'piece-of-cake',
    term: 'piece of cake',
    kind: 'idiom',
    cat: 'aleatoria',
    context_en: 'The exam was a piece of cake.',
    target: 'piece of cake',
    gloss_es: 'algo muy fácil',
    accept: ['piece of cake'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'hit-the-sack',
    term: 'hit the sack',
    kind: 'idiom',
    cat: 'aleatoria',
    context_en: 'I\'m exhausted — I\'m going to hit the sack.',
    target: 'hit the sack',
    gloss_es: 'irse a dormir',
    accept: ['hit the sack', 'hit the hay', 'hitting the sack'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'under-the-weather',
    term: 'under the weather',
    kind: 'idiom',
    cat: 'aleatoria',
    context_en: 'I feel a bit under the weather today.',
    target: 'under the weather',
    gloss_es: 'sentirse un poco enfermo o mal',
    accept: ['under the weather'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'cost-an-arm-and-a-leg',
    term: 'cost an arm and a leg',
    kind: 'idiom',
    cat: 'aleatoria',
    context_en: 'That car cost an arm and a leg.',
    target: 'cost an arm and a leg',
    gloss_es: 'costar carísimo',
    accept: ['cost an arm and a leg', 'an arm and a leg'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'once-in-a-blue-moon',
    term: 'once in a blue moon',
    kind: 'idiom',
    cat: 'aleatoria',
    context_en: 'We only meet once in a blue moon.',
    target: 'once in a blue moon',
    gloss_es: 'muy rara vez',
    accept: ['once in a blue moon', 'blue moon'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'break-a-leg',
    term: 'break a leg',
    kind: 'idiom',
    cat: 'aleatoria',
    context_en: 'Break a leg at the interview!',
    target: 'Break a leg',
    gloss_es: '\'¡mucha suerte!\' antes de un reto o actuación',
    accept: ['break a leg'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'call-it-a-day',
    term: 'call it a day',
    kind: 'idiom',
    cat: 'aleatoria',
    context_en: 'Let\'s call it a day.',
    target: 'call it a day',
    gloss_es: 'terminar por hoy',
    accept: ['call it a day', 'called it a day'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'ring-a-bell',
    term: 'ring a bell',
    kind: 'idiom',
    cat: 'aleatoria',
    context_en: 'That name rings a bell.',
    target: 'rings a bell',
    gloss_es: 'sonarte o recordar algo vagamente',
    accept: ['ring a bell', 'rings a bell', 'ring any bells'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'on-cloud-nine',
    term: 'on cloud nine',
    kind: 'idiom',
    cat: 'aleatoria',
    context_en: 'She\'s been on cloud nine since the news.',
    target: 'on cloud nine',
    gloss_es: 'súper feliz, en las nubes de la felicidad',
    accept: ['on cloud nine', 'cloud nine'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'bite-the-bullet',
    term: 'bite the bullet',
    kind: 'idiom',
    cat: 'aleatoria',
    context_en: 'I bit the bullet and went to the dentist.',
    target: 'bit the bullet',
    gloss_es: 'hacer de una vez algo difícil o desagradable',
    accept: ['bite the bullet', 'bit the bullet', 'biting the bullet'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'hang-in-there',
    term: 'hang in there',
    kind: 'idiom',
    cat: 'aleatoria',
    context_en: 'Hang in there, it gets better.',
    target: 'Hang in there',
    gloss_es: 'aguanta, no te rindas',
    accept: ['hang in there', 'hanging in there'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'the-last-straw',
    term: 'the last straw',
    kind: 'idiom',
    cat: 'aleatoria',
    context_en: 'That was the last straw.',
    target: 'the last straw',
    gloss_es: 'la gota que colma el vaso',
    accept: ['the last straw', 'last straw'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'blessing-in-disguise',
    term: 'a blessing in disguise',
    kind: 'idiom',
    cat: 'aleatoria',
    context_en: 'Losing that job was a blessing in disguise.',
    target: 'blessing in disguise',
    gloss_es: 'un mal que al final resulta bueno',
    accept: ['blessing in disguise', 'a blessing in disguise'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'on-the-fence',
    term: 'on the fence',
    kind: 'idiom',
    cat: 'aleatoria',
    context_en: 'I\'m still on the fence about it.',
    target: 'on the fence',
    gloss_es: 'indeciso, sin decidirse',
    accept: ['on the fence', 'sitting on the fence'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
  {
    id: 'let-the-cat-out-of-the-bag',
    term: 'let the cat out of the bag',
    kind: 'idiom',
    cat: 'aleatoria',
    context_en: 'He let the cat out of the bag about the party.',
    target: 'let the cat out of the bag',
    gloss_es: 'revelar un secreto sin querer',
    accept: ['let the cat out of the bag', 'cat out of the bag'],
    emoji: '✨',
    imagePrompt: 'sticker ilustrado die-cut generado (pack IA)',
  },
];

/** La categoría de un término (sin `cat` = 'dia-a-dia'). */
export function categoriaDe(t: SlangTerm): CategoriaId {
  return t.cat ?? 'dia-a-dia';
}

/** Las categorías que pinta el selector «explorar», en orden. Cada una tiene su
    propio ESTILO de sticker: día a día = flat, oficina = cartoon retro, cripto =
    pixel 8-bit, aleatoria = 3D plastilina. */
export const CATEGORIAS: { id: CategoriaId; label: string; desc: string }[] = [
  { id: 'dia-a-dia', label: 'Del día a día', desc: 'Slang y phrasal verbs de la calle y la vida diaria' },
  { id: 'oficina', label: 'En la oficina', desc: 'Los que se dicen en reuniones, correos y trabajo' },
  { id: 'crypto', label: 'Cripto', desc: 'La jerga de Crypto Twitter, trading y comunidades web3' },
  { id: 'aleatoria', label: 'Aleatoria', desc: 'Un cajón sorpresa de expresiones e idioms variados' },
];

/** El contexto con el término blanqueado, para el reto fill-in-the-blank. */
export function blankContext(t: SlangTerm): string {
  const blank = '_'.repeat(Math.max(4, t.target.length));
  // Reemplaza la primera aparición del target (case-insensitive) por el blank.
  const re = new RegExp(t.target.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i');
  return t.context_en.replace(re, blank);
}

/** Chequeo local tolerante: normaliza y compara contra accept. El juez real afina. */
export function isLocalMatch(t: SlangTerm, answer: string): boolean {
  const norm = (s: string) =>
    s
      .toLowerCase()
      .trim()
      .replace(/[.,!?;:'"]/g, '')
      .replace(/\s+/g, ' ');
  const a = norm(answer);
  if (!a) return false;
  return t.accept.some((x) => {
    const n = norm(x);
    return a === n || a.includes(n);
  });
}
