/* PACK POR TRABAJO · RECEPCIÓN — contenido puro, sin lógica.

   Recepción es la primera cara de la empresa: el visitante decide en diez
   segundos si el lugar es serio. Por eso acá el registro es de USTED aunque
   Alfred te hable de ti — la traducción va pa'l visitante, no pa' tú.

   Los ids van prefijados con `c-rec-`: son la llave del SRS (rodeo_a1_srs) y
   no pueden chocar con los del tronco ni con los de otro pack.

   Voz: Alfred, español latino neutro. why_es SIEMPRE con analogía y sin metalenguaje. */

import type { JobPack } from '@/content/a1/tipos';

export const PACK_RECEPCION: JobPack = {
  id: 'recepcion',
  nombre_es: 'Recepción',
  promesa_es: 'Recibir visitas, anunciar a quien llega y tomar el recado sin enredos.',
  emoji: '🛎️',
  intro_es: [
    'Recepción. Tú eres la primera cara que ve el que entra — y el que entra decide en diez segundos si esto es serio.',
    'Lo bueno es que es un guion cortito y siempre el mismo: recibes, anuncias, y si no está, tomas el recado.',
    'Ah, y ojo con las frases pa\' indicar el camino. Esas son las que más se piden y las que menos se estudian.',
  ],
  units: [
    {
      id: 'job-recepcion-u1',
      order: 104,
      title_es: 'La primera cara de la empresa',
      subtitle_es: 'Recibir, anunciar, orientar.',
      arc_es: 'Entra un visitante que no habla español. Sale sabiendo exactamente para dónde va.',
      emoji: '🚪',
      cardTheme: 'peach',
      icon: '🛎️',
      survival: false,
      companionSetup_es: [
        'Todo lo que pasa en tu mostrador cabe en tres momentos: recibir, anunciar y mandar pa\' el lado correcto.',
        'Son frases cortas y muy repetidas. Te las aprendes una vez y te sirven todos los días del año.',
      ],
      scenes: [
        {
          id: 'job-recepcion-s1-recibir',
          order: 1,
          title_es: 'Recibir visitas',
          scene_es: 'Se abre la puerta de vidrio y entra alguien que no conoces.',
          icon: '🚪',
          setup_es: [
            'Entra alguien. Antes de que abra la boca, la frase la tienes que soltar tú: eso ya te pone al mando.',
            'Después revisas si tiene cita, lo haces firmar y lo sientas. Cuatro pasos, cuatro frases.',
          ],
          analogy_es: 'Recibir es como abrir la puerta de tu casa: saludas, preguntas a quién busca y lo haces seguir a la sala. Nadie deja a la visita parada en la puerta averiguando sola.',
          chunks: [
            {
              id: 'c-rec-welcome-how-can-i-help',
              en: 'Welcome! How can I help you?',
              es: '¡Bienvenido! ¿En qué le ayudo?',
              sounds_es: 'guélcom! jáu kan ái jelp iú',
              why_es: 'Tu frase de puerta, y va antes de que el otro diga nada. El que saluda primero manda la conversación: el visitante entra perdido y tú le das el primer escalón. Con esa sola ya el lugar se siente ordenado.',
              sayWhen_es: 'Apenas alguien entra y se acerca al mostrador.',
              who_es: 'con la visita',
              frame: null,
              swaps: null,
              distractors_es: ['Welcome! How I can help you?', 'Welcome! How can I help to you?'],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: 'c-rec-do-you-have-appointment',
              en: 'Do you have an appointment?',
              es: '¿Tiene cita?',
              sounds_es: 'du iú jav an apóintment',
              why_es: 'La pregunta que ordena todo lo que sigue: con cita lo anuncias, sin cita tomas el recado. Es el semáforo de tu mostrador — de la respuesta depende para dónde arranca el resto.',
              sayWhen_es: 'Apenas te dicen a quién vienen a ver.',
              who_es: 'con la visita',
              frame: null,
              swaps: null,
              distractors_es: ['Do you have appointment?', 'Have you an appointment?'],
              cognateHook_es: 'Ojo: "appointment" suena a "apuntamiento" — úsalo de gancho, porque es justo eso: lo que quedó apuntado en la agenda.',
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: 'c-rec-sign-in-here',
              en: 'Please sign in here.',
              es: 'Firme aquí, por favor.',
              sounds_es: 'plís sáin in jíar',
              why_es: 'Una orden vuelta favor gracias al "please" adelante. Sin ese "please" suena a policía pidiendo papeles; con él, suena a la casa recibiéndote. Misma instrucción, dos mundos distintos.',
              sayWhen_es: 'Cuando le pasas el registro de visitantes.',
              who_es: 'con la visita',
              frame: null,
              swaps: null,
              distractors_es: ['Please sign here in.', 'Please signature here.'],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: 'c-rec-take-a-seat',
              en: 'Please take a seat.',
              es: 'Tome asiento, por favor.',
              sounds_es: 'plís téik a sit',
              why_es: 'La frase que convierte la espera en algo cómodo. Mientras el visitante está de pie se siente en el limbo; apenas se sienta, ya está adentro y espera tranquilo. Es la silla la que dice "ya te estamos atendiendo".',
              sayWhen_es: 'Mientras el visitante espera a que lo reciban.',
              who_es: 'con la visita',
              frame: null,
              swaps: null,
              distractors_es: ['Please take a chair.', 'Please sit a seat.'],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
        {
          id: 'job-recepcion-s2-anunciar',
          order: 2,
          title_es: 'Anunciar y tomar recados',
          scene_es: 'La visita pregunta por alguien. A veces está, a veces no.',
          icon: '📝',
          setup_es: [
            'Ya sabes a quién busca. Ahora hay dos caminos: o lo anuncias, o le explicas que no está.',
            'Y si no está, el recado. Ese pedacito es el que más se embarra en todas las recepciones del mundo.',
          ],
          analogy_es: 'Tomar un recado es como recibir un paquete de un vecino: mientras esté en tus manos es tuyo, y no queda entregado hasta que se lo pasas al dueño. Por eso siempre se promete la entrega en voz alta.',
          chunks: [
            {
              id: 'c-rec-let-her-know',
              en: "I'll let her know you're here.",
              es: 'Le aviso que llegó.',
              sounds_es: 'áil let jer nóu iúr jíar',
              why_es: 'El anuncio, y hace dos cosas de un tiro: le dice al visitante que ya te moviste, y le quita la ansiedad de "¿me habrán tenido en cuenta?". Es tocar el timbre de adentro estando afuera.',
              sayWhen_es: 'Cuando vas a avisarle a alguien que su visita llegó.',
              who_es: 'con la visita',
              frame: "I'll let ___ know you're here.",
              swaps: ['her', 'him', 'them'],
              distractors_es: ["I'll let her to know you're here.", "I'll let know her you're here."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: 'c-rec-shes-in-a-meeting',
              en: "She's in a meeting right now.",
              es: 'Está en una reunión en este momento.',
              sounds_es: 'shis in a mítin ráit náu',
              why_es: 'La forma amable de decir "no lo puede atender". El "right now" es clave: dice que es solo por ahora, no un portazo. Nadie se va molesto si siente que el no tiene fecha de vencimiento.',
              sayWhen_es: 'Cuando la persona buscada no está disponible.',
              who_es: 'con la visita',
              frame: "___ in a meeting right now.",
              swaps: ["She's", "He's", "They're"],
              distractors_es: ["She's in meeting right now.", "She's on a meeting right now."],
              cognateHook_es: 'Ojo con "meeting": suena a "mitin", pero es una reunión de trabajo, no un mitin político.',
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: 'c-rec-take-a-message',
              en: 'Can I take a message?',
              es: '¿Le tomo un recado?',
              sounds_es: 'kan ái téik a mésach',
              why_es: 'La salida elegante cuando no está la persona. En vez de dejar al visitante con las manos vacías, le ofreces algo — y el "no está" deja de ser un viaje perdido. Es la libretita del mostrador hecha frase.',
              sayWhen_es: 'Cuando la persona no está y hay que dejar razón.',
              who_es: 'con la visita',
              frame: null,
              swaps: null,
              distractors_es: ['Can I take a recado?', 'Can I get a message for you?'],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: 'c-rec-give-her-the-message',
              en: "I'll give her the message.",
              es: 'Yo le paso el mensaje.',
              sounds_es: 'áil guiv jer de mésach',
              why_es: 'El recibo del recado. Anotar no basta: hay que decir en voz alta que lo vas a entregar, porque eso es lo que el visitante se lleva pa\' la casa. Sin esa promesa se va con la duda de si sirvió de algo venir.',
              sayWhen_es: 'Después de anotar el recado, pa\' cerrar.',
              who_es: 'con la visita',
              frame: "I'll give ___ the message.",
              swaps: ['her', 'him', 'them'],
              distractors_es: ["I'll give the message to her it.", "I'll give her a message now."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
        {
          id: 'job-recepcion-s3-camino',
          order: 3,
          title_es: 'Indicar el camino',
          scene_es: 'Ya sabe a dónde va. Falta que sepa por dónde.',
          icon: '🧭',
          setup_es: [
            'Estas son las que más te van a pedir y las que menos se estudian: para dónde queda tal cosa.',
            'Se dicen con calma y señalando. Si el otro arranca dudando, se pierde en el segundo pasillo.',
          ],
          analogy_es: 'Dar indicaciones es como pasar una receta: se dice un paso, se deja respirar, y ahí sí el siguiente. Todo de corrido no se le queda a nadie.',
          chunks: [
            {
              id: 'c-rec-on-the-second-floor',
              en: "It's on the second floor.",
              es: 'Es en el segundo piso.',
              sounds_es: 'its on de sécond flóar',
              why_es: 'Tu molde pa\' mandar a alguien a un piso: cambias el número y ya está. Es la etiqueta del ascensor hecha frase, y es lo primero que hay que decir — el piso ordena todo lo demás.',
              sayWhen_es: 'Cuando preguntan en qué piso queda algo.',
              who_es: 'con la visita',
              frame: "It's on the ___ floor.",
              swaps: ['second', 'third', 'first'],
              distractors_es: ["It's in the second floor.", "It's on the two floor."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: 'c-rec-down-the-hall',
              en: "It's down the hall on the right.",
              es: 'Es por el pasillo a la derecha.',
              sounds_es: 'its dáun de jol on de ráit',
              why_es: '"down the hall" no es "abajo": es derecho por el pasillo, como cuando dices "sigue derecho" aunque el piso esté plano. Y el lado va de último, que es el orden en que la persona lo va a necesitar: primero camina, después voltea.',
              sayWhen_es: 'Cuando explicas cómo llegar en el mismo piso.',
              who_es: 'con la visita',
              frame: "It's down the hall on the ___.",
              swaps: ['right', 'left'],
              distractors_es: ["It's down the hall in the right.", "It's down the hall at right."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: 'c-rec-follow-me',
              en: 'Follow me, please.',
              es: 'Sígame, por favor.',
              sounds_es: 'fólou mi, plís',
              why_es: 'Cuando la explicación se enreda, dejas de explicar y caminas. Es la que salva cualquier indicación fallida: en vez de tres frases que el otro no entendió, veinte pasos juntos y llegaron.',
              sayWhen_es: 'Cuando prefieres acompañar en vez de explicar.',
              who_es: 'con la visita',
              frame: null,
              swaps: null,
              distractors_es: ['Follow to me, please.', 'Follow me the please.'],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
      ],
      task: {
        id: 'job-recepcion-u1-task',
        intro_es: 'Listo. Se abre la puerta de vidrio, entra un visitante con maletín y viene derecho hacia ti…',
        steps: [
          {
            goal_es: 'Se acerca al mostrador y todavía no dice nada. Arranca tú.',
            answerChunkId: 'c-rec-welcome-how-can-i-help',
            reaction_es: '¡Eso! Saludaste primero y ya quedaste al mando.',
          },
          {
            goal_es: 'Viene a ver a la gerente, y ella sí está. Avísale que llegó.',
            answerChunkId: 'c-rec-let-her-know',
            reaction_es: 'Perfecto. Con eso el visitante ya sabe que te moviste.',
          },
          {
            goal_es: 'Le toca subir a la sala de juntas. Dile en qué piso queda.',
            answerChunkId: 'c-rec-on-the-second-floor',
            reaction_es: 'De una. Con el piso primero, ya no se pierde.',
          },
        ],
        done_es: 'Ya sabes SER LA PRIMERA CARA DE LA EMPRESA EN INGLÉS. ✓',
      },
    },
  ],
};
