/* PACK POR TRABAJO · SOPORTE — contenido puro, sin lógica.

   Soporte es el único rol donde el inglés te llega ENOJADO. Por eso la mitad
   de estas frases no resuelven nada técnico: bajan la temperatura. Primero se
   calma al cliente, después se arregla el problema.

   Los ids van prefijados con `c-sop-`: son la llave del SRS (rodeo_a1_srs) y
   no pueden chocar con los del tronco ni con los de otro pack.

   Voz: Alfred, español latino neutro. why_es SIEMPRE con analogía y sin metalenguaje. */

import type { JobPack } from '@/content/a1/tipos';

export const PACK_SOPORTE: JobPack = {
  id: 'soporte',
  nombre_es: 'Soporte',
  promesa_es: 'Atender el ticket, sacarle los datos al cliente y cerrar con solución.',
  emoji: '🎧',
  intro_es: [
    'Soporte, ¿cierto? Ese es el trabajo donde el inglés te llega bravo y con prisa.',
    'Pero fíjate en algo: la mitad de lo que vas a decir no arregla nada técnico — solo baja la temperatura. Y eso es lo que salva el ticket.',
    'Te doy el saludo, cómo sacarle los datos sin pelear, y cómo cerrar dejando al cliente contento.',
  ],
  units: [
    {
      id: 'job-soporte-u1',
      order: 103,
      title_es: 'El ticket, de principio a fin',
      subtitle_es: 'Calmar, entender, resolver.',
      arc_es: 'Entra un cliente bravo. Sale un cliente que dice gracias.',
      emoji: '🎫',
      cardTheme: 'lavender',
      icon: '🛠️',
      survival: false,
      companionSetup_es: [
        'Todo ticket es el mismo baile: saludas, entiendes qué pasó, y cierras con algo resuelto.',
        'Vamos por esos tres momentos. Y ojo con el primero, que es donde se gana o se pierde todo.',
      ],
      scenes: [
        {
          id: 'job-soporte-s1-atender',
          order: 1,
          title_es: 'Atender el ticket',
          scene_es: 'Entra un chat. Del otro lado hay alguien que ya lleva rato esperando.',
          icon: '👋',
          setup_es: [
            'Los primeros diez segundos deciden todo. Si el cliente siente que lo estás atendiendo, se calma solito.',
            'Tres frases: abres, reconoces que la embarraron, y avisas que vas a mirar.',
          ],
          analogy_es: 'Atender un ticket bravo es como recibir a alguien empapado en la puerta: primero le pasas la toalla, después preguntas por qué salió sin sombrilla. Al revés, se te va.',
          chunks: [
            {
              id: 'c-sop-how-can-i-help',
              en: 'How can I help you today?',
              es: '¿En qué te puedo ayudar hoy?',
              sounds_es: 'jáu kan ái jelp iú tudéi',
              why_es: 'Tu frase de apertura, y no falla nunca. Fíjate que no pregunta "¿qué pasó?" sino qué puedes hacer VOS: desde el primer segundo te pones del lado del cliente, no enfrente. Es abrir la puerta y hacerse a un lado.',
              sayWhen_es: 'Al abrir cualquier ticket o llamada.',
              who_es: 'con el cliente',
              frame: null,
              swaps: null,
              distractors_es: ['How can I help to you today?', 'How I can help you today?'],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: 'c-sop-sorry-about-that',
              en: "I'm sorry about that.",
              es: 'Lamento mucho eso.',
              sounds_es: 'áim sóri abáut dat',
              why_es: 'El extintor. No estás admitiendo que la culpa es tuya: estás diciendo que te importa lo que le pasó. La rabia del cliente necesita que alguien la reciba — recibila con esta y ya baja la mitad.',
              sayWhen_es: 'Apenas el cliente cuenta su problema.',
              who_es: 'con el cliente',
              frame: null,
              swaps: null,
              distractors_es: ["I'm sorry for that thing happened.", "I'm sorry of that."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: true,
            },
            {
              id: 'c-sop-let-me-check',
              en: 'Let me check that for you.',
              es: 'Déjame revisarlo.',
              sounds_es: 'let mi chek dat for iú',
              why_es: 'Tu salvavidas cuando no sabes la respuesta todavía. Compra tiempo SIN dejar al cliente colgado, porque el "for you" le dice que alguien ya está haciendo algo por él. Es el "ya voy" del mesero: no llegó el plato, pero sabes que viene.',
              sayWhen_es: 'Cuando necesitas mirar algo antes de responder.',
              who_es: 'con el cliente',
              frame: null,
              swaps: null,
              distractors_es: ['Let me to check that for you.', 'Let me check that to you.'],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: true,
            },
          ],
        },
        {
          id: 'job-soporte-s2-datos',
          order: 2,
          title_es: 'Sacarle los datos al cliente',
          scene_es: 'Te contó el problema, pero sin un solo dato útil.',
          icon: '🔎',
          setup_es: [
            'Ya sabes que algo falló, pero no tienes con qué buscarlo. Toca pedir datos sin sonar a interrogatorio.',
            'El truco está en pedir de a uno. Tres preguntas de golpe y el cliente se enreda o se enoja.',
          ],
          analogy_es: 'Pedir datos es como pedir la dirección de una casa: sin el número no llegas, por más que el otro te insista en que es la de la reja verde. Preguntas el número, y ahí sí arrancas.',
          chunks: [
            {
              id: 'c-sop-your-order-number',
              en: 'Can I have your order number?',
              es: '¿Me das tu número de orden?',
              sounds_es: 'kan ái jav iór órder námber',
              why_es: 'La llave pa\' encontrar al cliente en el sistema, pedida con educación. "Can I have…" es tu molde pa\' pedir CUALQUIER dato: le cambias la cola y sirve pa\' el correo, el apellido, lo que sea. Uno solo por vez.',
              sayWhen_es: 'Cuando necesitas un dato pa\' poder buscar.',
              who_es: 'con el cliente',
              frame: 'Can I have your ___?',
              swaps: ['order number', 'email', 'last name'],
              distractors_es: ['Can I have the your order number?', 'Can I take your order number?'],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: 'c-sop-what-happened',
              en: 'What happened exactly?',
              es: '¿Qué pasó exactamente?',
              sounds_es: 'guát jápend eksáktli',
              why_es: 'El "exactly" es el que hace el trabajo: le pide al cliente que baje del "no me funciona nada" al detalle de verdad. Es como pedirle a alguien que señale dónde le duele en vez de decir "me duele todo".',
              sayWhen_es: 'Cuando el cliente cuenta el problema muy en general.',
              who_es: 'con el cliente',
              frame: null,
              swaps: null,
              distractors_es: ['What happens exactly?', 'What did happened exactly?'],
              cognateHook_es: '"exactly" es exactamente. Se escribe casi igual y se entiende de una.',
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: 'c-sop-send-a-screenshot',
              en: 'Can you send me a screenshot?',
              es: '¿Me mandas una captura?',
              sounds_es: 'kan iú send mi a scrínshot',
              why_es: 'La foto vale más que veinte mensajes explicando. "screenshot" es literal la pantalla disparada, una foto de lo que el cliente está viendo — y con eso te ahorras la mitad del ticket.',
              sayWhen_es: 'Cuando la explicación no te alcanza y necesitas ver.',
              who_es: 'con el cliente',
              frame: null,
              swaps: null,
              distractors_es: ['Can you send to me a screenshot?', 'Can you send me an screenshot?'],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
        {
          id: 'job-soporte-s3-escalar',
          order: 3,
          title_es: 'Escalar y despedir con solución',
          scene_es: 'El problema te quedó grande, o ya lo resolviste. Toca cerrar bien.',
          icon: '✅',
          setup_es: [
            'Hay tickets que te quedan grandes. Pasarlos NO es fracasar: fracasar es tener al cliente una hora dando vueltas contigo.',
            'Y si lo resolviste, hay que cerrar bien. Un cierre flojo daña un ticket bueno.',
          ],
          analogy_es: 'Escalar es como pasar la llamada en una casa: "espera que te paso a mi mamá, que ella sí sabe". Nadie se ofende — lo que ofende es que le insistas sin saber.',
          chunks: [
            {
              id: 'c-sop-transfer-you',
              en: 'Let me transfer you to my manager.',
              es: 'Te paso con mi jefe.',
              sounds_es: 'let mi tránsfer iú tu mái mánayer',
              why_es: 'Pasar el ticket no es rendirse: es reconocer que hay alguien que lo resuelve más rápido. Decilo con seguridad, como quien entrega una posta en una carrera — no como quien se quita un problema de encima.',
              sayWhen_es: 'Cuando el caso te queda grande y toca pasarlo.',
              who_es: 'con el cliente',
              frame: 'Let me transfer you to ___.',
              swaps: ['my manager', 'the tech team', 'billing'],
              distractors_es: ['Let me transfer you with my manager.', 'Let me transfer to you my manager.'],
              cognateHook_es: '"transfer" es transferir. Igualita, y acá se usa pa\' pasar llamadas.',
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: 'c-sop-team-will-fix-it',
              en: 'Our team will fix it today.',
              es: 'Mi equipo lo arregla hoy.',
              sounds_es: 'áuar tim güil fix it tudéi',
              why_es: 'Promesa con fecha, que es la única clase de promesa que calma a un cliente. "Our team" reparte el peso: no quedas tú solito cargando el compromiso, responde la empresa entera.',
              sayWhen_es: 'Cuando ya sabes cuándo se resuelve y puedes comprometerte.',
              who_es: 'con el cliente',
              frame: 'Our team will fix it ___.',
              swaps: ['today', 'tomorrow', 'this week'],
              distractors_es: ['Our team will fix it in today.', 'Our team fix it today.'],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: 'c-sop-is-it-working-now',
              en: 'Is it working now?',
              es: '¿Ya te funciona?',
              sounds_es: 'is it guórkin náu',
              why_es: 'La pregunta que cierra de verdad. Si no la haces, el ticket queda cerrado en tu pantalla pero abierto en la cabeza del cliente — y vuelve mañana más bravo. Es probar la puerta después de arreglar la chapa.',
              sayWhen_es: 'Después de aplicar la solución, antes de cerrar.',
              who_es: 'con el cliente',
              frame: null,
              swaps: null,
              distractors_es: ['Is it work now?', 'Does it working now?'],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: 'c-sop-anything-else',
              en: 'Anything else I can help with?',
              es: '¿Algo más en que te ayude?',
              sounds_es: 'énizin els ái kan jelp güid',
              why_es: 'El cierre elegante del soporte. Regala una última puerta abierta y por eso el cliente se va sintiendo bien atendido, no despachado. Es el "¿le sirvo algo más?" del mesero antes de traer la cuenta.',
              sayWhen_es: 'Al final del ticket, antes de despedirte.',
              who_es: 'con el cliente',
              frame: null,
              swaps: null,
              distractors_es: ['Anything more I can help with?', 'Something else I can help?'],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
      ],
      task: {
        id: 'job-soporte-u1-task',
        intro_es: 'Bueno, entra un chat y el cliente ya viene caliente. Fresco, tú tienes con qué…',
        steps: [
          {
            goal_es: 'Te acaba de contar que lleva tres días con el problema. Reconocelo antes de nada.',
            answerChunkId: 'c-sop-sorry-about-that',
            reaction_es: '¡Eso! Con esa sola frase ya le bajaste la mitad de la rabia.',
          },
          {
            goal_es: 'No lo encuentras en el sistema. Pedile el dato que te falta.',
            answerChunkId: 'c-sop-your-order-number',
            reaction_es: 'Perfecto, y de a uno. Tres preguntas de golpe lo habrían enredado.',
          },
          {
            goal_es: 'Ya aplicaste la solución. Confirma antes de cerrar.',
            answerChunkId: 'c-sop-is-it-working-now',
            reaction_es: 'Así se cierra. Sin esa pregunta el ticket vuelve mañana.',
          },
        ],
        done_es: 'Ya sabes LLEVAR UN TICKET DE PUNTA A PUNTA. ✓',
      },
    },
  ],
};
