/* PACK POR TRABAJO · TECH / DEV — contenido puro, sin lógica.

   El tronco (A1_CURSO) te enseña a llegar, saludar y sobrevivir la reunión.
   Este pack es lo que se dice DESPUÉS: el standup de las 9, el bug que se te
   coló a producción y el "prestame un ojo" cuando ya llevas dos horas pegado.

   Los ids de chunk van prefijados con `c-tech-` a propósito: son la llave del
   SRS (rodeo_a1_srs) y no pueden chocar nunca con los del tronco. Renombrar
   uno le borra el progreso a quien ya lo tenía.

   Voz: Alfred, español latino neutro. why_es SIEMPRE con analogía y sin metalenguaje. */

import type { JobPack } from '@/content/a1/tipos';

export const PACK_TECH: JobPack = {
  id: 'tech',
  nombre_es: 'Tech / Dev',
  promesa_es: 'Sobrevivir el standup, reportar un bug y pedir ayuda sin quedar de mudo.',
  emoji: '💻',
  intro_es: [
    'Ah, tú eres de los que programan. Fresco, ese inglés es más fácil de lo que parece.',
    'La mitad de las palabras ya las dices en español: bug, deploy, push, build. Lo que falta es la frasecita alrededor.',
    'Te doy el standup, el reporte del bug y el "echame una mano". Con eso pasas la semana.',
  ],
  units: [
    {
      id: 'job-tech-u1',
      order: 101,
      title_es: 'El día a día del dev',
      subtitle_es: 'Standup, bugs y pedir una mano.',
      arc_es: 'Ya no eres el que asiente en el standup. Ahora hablas y te entienden.',
      emoji: '🐛',
      cardTheme: 'blue',
      icon: '💻',
      survival: false,
      companionSetup_es: [
        'Arrancamos por el standup, que es lo que te toca TODOS los días a la misma hora.',
        'Después el bug y el pedir ayuda. Son tres momentos, tres paquetes de frases. Nada más.',
      ],
      scenes: [
        {
          id: 'job-tech-s1-standup',
          order: 1,
          title_es: 'El standup de las 9',
          scene_es: 'Todos parados en círculo (o en el Meet) y te toca hablar 30 segundos.',
          icon: '⏱️',
          setup_es: [
            'El standup es cortico y siempre igual: qué hiciste ayer, qué haces hoy, qué te tiene trabado.',
            'Tres frases y ya. Ni una más, que el que se alarga en el standup cae mal.',
          ],
          analogy_es: 'El standup es como el parte del vigilante al cambiar el turno: lo de anoche, lo de hoy y qué quedó dañado. Nadie pide la novela completa.',
          chunks: [
            {
              id: 'c-tech-yesterday-worked-on',
              en: 'Yesterday I worked on the login.',
              es: 'Ayer trabajé en el login.',
              sounds_es: 'iésterdei ái guórkt on de lóguin',
              why_es: 'La primera de las tres del standup, y siempre arranca igual: "Yesterday I worked on…". Le cuelgas al final lo que tocaste ayer y listo. Es un molde, no una frase que haya que inventar cada mañana.',
              sayWhen_es: 'En el standup, contando lo de ayer.',
              who_es: 'con el equipo',
              frame: 'Yesterday I worked on ___.',
              swaps: ['the login', 'the API', 'the tests'],
              distractors_es: ['Yesterday I work on the login.', 'Yesterday I worked in the login.'],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: 'c-tech-today-working-on',
              en: "Today I'm working on the API.",
              es: 'Hoy estoy con el API.',
              sounds_es: "tudéi áim guórkin on de éi-pi-ái",
              why_es: 'La segunda del standup. Ojo al cambio de sabor: ayer se acabó, hoy está pasando ahorita mismo — por eso suena distinto aunque sea el mismo cuento. Como decir "ayer llovió" y "hoy está lloviendo".',
              sayWhen_es: 'En el standup, contando lo de hoy.',
              who_es: 'con el equipo',
              frame: "Today I'm working on ___.",
              swaps: ['the API', 'the login', 'a bug'],
              distractors_es: ['Today I work on the API.', "Today I'm working in the API."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: 'c-tech-im-blocked',
              en: "I'm blocked on this.",
              es: 'Estoy trabado con esto.',
              sounds_es: 'áim blókt on dis',
              why_es: 'La tercera del standup, y la más importante. Decir que estás trabado NO es confesar que eres malo: es prender la luz del carro varado pa\' que alguien pare a ayudarte. El que se queda callado dos días es el que queda mal.',
              sayWhen_es: 'Cuando algo te tiene detenido y necesitas que lo sepan.',
              who_es: 'con el equipo',
              frame: null,
              swaps: null,
              distractors_es: ["I'm blocked in this.", "I have blocked on this."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: true,
            },
            {
              id: 'c-tech-no-blockers',
              en: 'No blockers on my side.',
              es: 'Por mi lado, nada trabado.',
              sounds_es: 'nou blókers on mái sáid',
              why_es: 'La respuesta de "todo bien, sigo". "On my side" es "por mi lado": marcas tu pedacito de cancha y no respondes por el de los demás. Cortica, y cierras tu turno sin enredarte.',
              sayWhen_es: 'En el standup, cuando nada te detiene.',
              who_es: 'con el equipo',
              frame: null,
              swaps: null,
              distractors_es: ['No blockers in my side.', 'Not blockers on my side.'],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
        {
          id: 'job-tech-s2-bug',
          order: 2,
          title_es: 'Reportar un bug',
          scene_es: 'Algo se rompió y te toca avisar antes de que lo note el cliente.',
          icon: '🚨',
          setup_es: [
            'Se rompió algo. Lo primero no es arreglarlo: es AVISAR, y avisar clarito.',
            'Y sí, la frase mítica del "en mi máquina sí funciona" también te la enseño. Se usa, pero con cuidado.',
          ],
          analogy_es: 'Reportar un bug es como avisar de una fuga de agua: dices QUÉ se moja y DÓNDE. Si solo gritas "¡ayuda!", el plomero llega y no sabe ni por dónde empezar.',
          chunks: [
            {
              id: 'c-tech-found-a-bug',
              en: 'I found a bug in production.',
              es: 'Encontré un bug en producción.',
              sounds_es: 'ái fáund a bag in prodákshon',
              why_es: '"bug" es bicho: el gringo se imagina un animalito metido en la máquina dañándola. Decilo con el DÓNDE pegado (in production, in the login) — sin el dónde, el aviso no sirve pa\' nada.',
              sayWhen_es: 'Cuando encuentras algo roto y toca avisar.',
              who_es: 'con el equipo',
              frame: 'I found a bug in ___.',
              swaps: ['production', 'the login', 'the app'],
              distractors_es: ['I find a bug in production.', 'I found a bug on production.'],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: 'c-tech-build-not-working',
              en: 'The build is not working.',
              es: 'El build no está funcionando.',
              sounds_es: 'de bild is not guórkin',
              why_es: 'Tu molde pa\' decir que algo NO sirve, sin drama y sin culpar a nadie. Le cambias el sujeto —the build, the app, the server— y ya tienes reporte pa\' cualquier cosa que se caiga.',
              sayWhen_es: 'Cuando algo dejó de funcionar.',
              who_es: 'con el equipo',
              frame: '___ is not working.',
              swaps: ['The build', 'The app', 'The server'],
              distractors_es: ['The build is not work.', 'The build not is working.'],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: 'c-tech-works-on-my-machine',
              en: 'It works on my machine.',
              es: 'En mi máquina sí funciona.',
              sounds_es: 'it guórks on mái mashín',
              why_es: 'El chiste más viejo del gremio, y por eso hay que decirlo con sonrisa. Solita suena a "el problema es tuyo"; pegale un "let\'s check together" detrás y pasas de escurrir el bulto a ser el que ayuda.',
              sayWhen_es: 'Cuando a ti te corre bien y al otro no.',
              who_es: 'con un compañero',
              frame: null,
              swaps: null,
              distractors_es: ['It work on my machine.', 'It works in my machine.'],
              cognateHook_es: 'Ojo: "machine" es máquina, sí — pero acá le dicen así al computador, no a una máquina de coser.',
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: 'c-tech-can-you-reproduce',
              en: 'Can you reproduce it?',
              es: '¿Lo puedes reproducir?',
              sounds_es: 'kan iú riprodiús it',
              why_es: '"reproduce" acá es volver a hacer que pase, como repetir la jugada en cámara lenta pa\' ver dónde se cayó. Si el bug no se repite, no hay qué arreglar: por eso esta pregunta es la primera de toda investigación.',
              sayWhen_es: 'Cuando te reportan algo y necesitas verlo pasar.',
              who_es: 'con el equipo',
              frame: null,
              swaps: null,
              distractors_es: ['Can you reproduce them?', 'Do you can reproduce it?'],
              cognateHook_es: 'Se parece a "reproducir" y significa casi lo mismo: hacer que vuelva a pasar.',
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
        {
          id: 'job-tech-s3-ayuda',
          order: 3,
          title_es: 'Pedir una mano con el código',
          scene_es: 'Llevas dos horas pegado en lo mismo. Toca pedir ayuda.',
          icon: '🤝',
          setup_es: [
            'Dos horas pegado en lo mismo ya es demasiado. Acá pedir ayuda no es rendirse, es sentido común.',
            'Tres frases: que te miren, que se sienten contigo, y avisar cuando ya lo arreglaste.',
          ],
          analogy_es: 'Pedir que te miren el código es como pedirle a alguien que relea tu mensaje antes de mandarlo: tú ya no ves el error porque llevas una hora mirándolo. Ojos frescos lo cazan en diez segundos.',
          chunks: [
            {
              id: 'c-tech-take-a-look',
              en: 'Can you take a look?',
              es: '¿Le puedes echar un ojo?',
              sounds_es: 'kan iú téik a luk',
              why_es: 'El "echame un ojo" de toda la vida. Pide poquito —una mirada, no que te resuelvan el día— y por eso casi nadie te dice que no. Es la forma más barata de pedir ayuda que existe.',
              sayWhen_es: 'Cuando quieres que alguien te revise algo.',
              who_es: 'con un compañero',
              frame: null,
              swaps: null,
              distractors_es: ['Can you take a see?', 'Can you look a take?'],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: true,
            },
            {
              id: 'c-tech-pair-on-this',
              en: 'Can we pair on this?',
              es: '¿Lo hacemos juntos?',
              sounds_es: 'kan güi per on dis',
              why_es: '"pair" es de a dos, como bailar: uno maneja el teclado y el otro va viendo el camino. Pedirlo no es pedir que te lo hagan — es pedir compañía mientras tú manejas.',
              sayWhen_es: 'Cuando quieres resolver algo acompañado.',
              who_es: 'con un compañero',
              frame: null,
              swaps: null,
              distractors_es: ['Can we pair in this?', 'Can we pair this?'],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: 'c-tech-pushed-the-fix',
              en: 'I pushed the fix.',
              es: 'Ya subí el arreglo.',
              sounds_es: 'ái pusht de fix',
              why_es: 'El aviso de "listo, ya está arriba". Cortica y con peso: cierra el asunto y le dice al equipo que puede seguir. Sin este aviso, el bug sigue vivo en la cabeza de todos aunque tú ya lo hayas matado.',
              sayWhen_es: 'Cuando ya subiste la solución.',
              who_es: 'con el equipo',
              frame: 'I pushed the ___.',
              swaps: ['fix', 'changes', 'tests'],
              distractors_es: ['I push the fix.', 'I pushed the fixed.'],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
      ],
      task: {
        id: 'job-tech-u1-task',
        intro_es: 'Bueno, son las 9 y arranca el standup. Después se cae algo. Día normal, pues…',
        steps: [
          {
            goal_es: 'Te toca tu turno en el standup. Cuenta en qué andas hoy.',
            answerChunkId: 'c-tech-today-working-on',
            reaction_es: '¡Eso! Treinta segundos y ya cumpliste.',
          },
          {
            goal_es: 'Se cayó algo en producción. Avisale al equipo.',
            answerChunkId: 'c-tech-found-a-bug',
            reaction_es: 'Perfecto, y con el "in production" pegado. Así saben dónde buscar.',
          },
          {
            goal_es: 'Llevas dos horas pegado. Pedile a alguien que te revise.',
            answerChunkId: 'c-tech-take-a-look',
            reaction_es: 'De una. Dos horas pegado ya es mucho — y nadie te va a decir que no.',
          },
        ],
        done_es: 'Ya sabes MOVERTE COMO DEV EN INGLÉS. ✓',
      },
    },
  ],
};
