/* PACK POR TRABAJO · VENTAS — contenido puro, sin lógica.

   Vender en inglés no es saber más palabras: es saber las CUATRO frases del
   guion (qué hacemos, cuánto vale, ¿arrancamos?, te escribo el viernes) y
   soltarlas sin trabarse. Eso es lo que hay acá.

   Los ids van prefijados con `c-ven-`: son la llave del SRS (rodeo_a1_srs) y
   no pueden chocar con los del tronco ni con los de otro pack.

   Voz: Alfred, español latino neutro. why_es SIEMPRE con analogía y sin metalenguaje. */

import type { JobPack } from '@/content/a1/tipos';

export const PACK_VENTAS: JobPack = {
  id: 'ventas',
  nombre_es: 'Ventas',
  promesa_es: 'Presentar el producto, hablar de plata y cerrar la llamada sin sudar.',
  emoji: '📈',
  intro_es: [
    'Uy, ventas. Tú ya sabes vender — lo que te falta es el idioma, no la maña.',
    'Y en inglés la venta es un guion cortico: qué hacemos, cuánto vale, ¿arrancamos?, y el "te escribo el viernes".',
    'Te doy esas cuatro puertas. Lo de convencer ya lo tienes tú.',
  ],
  units: [
    {
      id: 'job-ventas-u1',
      order: 102,
      title_es: 'La llamada de venta, de punta a punta',
      subtitle_es: 'Del "hola" al "te escribo el viernes".',
      arc_es: 'Entras a la llamada con el guion en la mano. Sales con un próximo paso.',
      emoji: '🤝',
      cardTheme: 'green',
      icon: '📞',
      survival: false,
      companionSetup_es: [
        'Una llamada de venta tiene tres tramos: muestras, hablas de plata, y cierras con un próximo paso.',
        'Si te aprendes uno por tramo ya puedes sostener la llamada entera. Vamos por partes.',
      ],
      scenes: [
        {
          id: 'job-ventas-s1-presentar',
          order: 1,
          title_es: 'Presentar el producto',
          scene_es: 'Se abre la llamada. Tienes dos minutos pa\' que entiendan qué vendes.',
          icon: '✨',
          setup_es: [
            'Los primeros dos minutos no son pa\' lucirte: son pa\' que el otro entienda qué le vendes.',
            'Fíjate que las tres frases hablan del CLIENTE, no del producto. Ese es el truco.',
          ],
          analogy_es: 'Presentar el producto es como mostrar una casa: no arrancas con los metros cuadrados, arrancas con "mira la luz que entra por acá". Primero lo que gana el otro, después la ficha técnica.',
          chunks: [
            {
              id: 'c-ven-let-me-show-you',
              en: 'Let me show you what we do.',
              es: 'Te muestro qué hacemos.',
              sounds_es: 'let mi shóu iú guát güi du',
              why_es: 'Tu puerta de entrada, suavecita. "Let me…" es pedir permiso y arrancar en el mismo movimiento — como cuando abres la puerta del carro y dices "subite, te llevo". No preguntas si quieres mostrar: ya estás mostrando.',
              sayWhen_es: 'Al arrancar la presentación del producto.',
              who_es: 'con el cliente',
              frame: 'Let me show you ___.',
              swaps: ['what we do', 'the product', 'how it works'],
              distractors_es: ['Let me show to you what we do.', 'Let me showing you what we do.'],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: 'c-ven-it-helps-you',
              en: 'It helps you save time.',
              es: 'Te ayuda a ahorrar tiempo.',
              sounds_es: 'it jelps iú séiv táim',
              why_es: 'La frase que convierte el producto en un beneficio. Ojo al orden: primero el CLIENTE ("you") y después lo que gana. Nadie compra un taladro: compra el hueco en la pared.',
              sayWhen_es: 'Cuando explicas para qué le sirve al cliente.',
              who_es: 'con el cliente',
              frame: 'It helps you ___.',
              swaps: ['save time', 'save money', 'sell more'],
              distractors_es: ['It helps you to saving time.', 'It helps to you save time.'],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: 'c-ven-any-questions',
              en: 'Do you have any questions?',
              es: '¿Tienes alguna pregunta?',
              sounds_es: 'du iú jav éni kuéschons',
              why_es: 'El respiro que separa tu discurso de la conversación de verdad. Si no lo haces, sigues hablando solo y no te enteras de que el otro se perdió hace rato. Es abrir la ventana pa\' que entre aire.',
              sayWhen_es: 'Al terminar de explicar, antes de seguir.',
              who_es: 'con el cliente',
              frame: null,
              swaps: null,
              distractors_es: ['Do you have some questions?', 'Have you any question?'],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
        {
          id: 'job-ventas-s2-precio',
          order: 2,
          title_es: 'Precio y descuento',
          scene_es: 'Llegó la pregunta incómoda: "¿y cuánto vale?".',
          icon: '💵',
          setup_es: [
            'Llegó la plata. Acá el que titubea pierde: se dice el precio derechito y se calla.',
            'Y si toca ceder, hay una forma de ofrecer descuento sin regalar el producto.',
          ],
          analogy_es: 'Decir el precio es como servir un tinto: se pone en la mesa y se suelta la taza. El que se queda con la taza en la mano, temblando, hace que el otro desconfíe del tinto.',
          chunks: [
            {
              id: 'c-ven-price-per-month',
              en: "It's fifty dollars per month.",
              es: 'Son cincuenta dólares al mes.',
              sounds_es: 'its fífti dólars per manz',
              why_es: 'El precio, derechito y sin adornos. "per month" es el "al mes" de la factura del gas: cambias el número y sirve pa\' cualquier plan. Decilo completo y haz silencio — el silencio después del precio es parte de la venta.',
              sayWhen_es: 'Cuando te preguntan cuánto vale.',
              who_es: 'con el cliente',
              frame: "It's ___ per month.",
              swaps: ['fifty dollars', 'ninety dollars', 'twenty dollars'],
              distractors_es: ["It's fifty dollars for month.", "It's fifty dollars at month."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: 'c-ven-offer-a-discount',
              en: 'We can offer a discount.',
              es: 'Podemos darte un descuento.',
              sounds_es: 'güi kan ófer a discáunt',
              why_es: 'Fíjate que dice "we", no "I": el descuento lo da la empresa, no tú de tu bolsillo. Eso te protege — no quedas de blandito ni te lo van a pedir cada vez que hablen contigo.',
              sayWhen_es: 'Cuando el precio le aprieta y puedes ceder un poco.',
              who_es: 'con el cliente',
              frame: null,
              swaps: null,
              distractors_es: ['We can offer you a discount price down.', 'We can to offer a discount.'],
              cognateHook_es: '"discount" es descuento, igualito. Esa te la regalan.',
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: 'c-ven-fit-your-budget',
              en: 'Does that fit your budget?',
              es: '¿Eso te cabe en el presupuesto?',
              sounds_es: 'das dat fit iór bádyet',
              why_es: '"fit" es caber, como un zapato. En vez de preguntar "¿lo vas a comprar?" —que asusta— preguntas si le queda cómodo. Es la misma pregunta con guantes, y el otro te contesta la verdad.',
              sayWhen_es: 'Después de decir el precio, pa\' medir la reacción.',
              who_es: 'con el cliente',
              frame: null,
              swaps: null,
              distractors_es: ['Does that fit in your budget money?', 'Do that fit your budget?'],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
        {
          id: 'job-ventas-s3-cerrar',
          order: 3,
          title_es: 'Cerrar y hacer follow-up',
          scene_es: 'La llamada se va acabando. Toca dejar amarrado el próximo paso.',
          icon: '📅',
          setup_es: [
            'Una llamada que termina sin próximo paso es una llamada perdida, así hayan quedado encantados.',
            'Estas cuatro amarran: el sí, la propuesta, la fecha del recordatorio y el gracias.',
          ],
          analogy_es: 'Cerrar sin próximo paso es como dejar el carro en bajada sin freno de mano: se ve bien parqueado hasta que voltéas y ya se fue rodando.',
          chunks: [
            {
              id: 'c-ven-ready-to-start',
              en: 'Are you ready to start?',
              es: '¿Arrancamos?',
              sounds_es: 'ar iú rédi tu start',
              why_es: 'El cierre, y suena a invitación en vez de a presión. No pregunta "¿me compras?", pregunta si ya está listo — como cuando el taxi ya está abajo y solo falta que bajes. La decisión ya se ve tomada.',
              sayWhen_es: 'Cuando ves que ya está convencido.',
              who_es: 'con el cliente',
              frame: null,
              swaps: null,
              distractors_es: ['Are you ready for start?', 'Do you ready to start?'],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: 'c-ven-send-the-proposal',
              en: "I'll send you the proposal today.",
              es: 'Te mando la propuesta hoy.',
              sounds_es: 'áil send iú de propóusal tudéi',
              why_es: 'Una promesa con fecha pegada. Sin el "today" la frase se vuelve humo y la propuesta se te queda en borradores. Poner el cuándo es lo que la convierte en compromiso.',
              sayWhen_es: 'Cuando quedas de mandar algo por escrito.',
              who_es: 'con el cliente',
              frame: "I'll send you the proposal ___.",
              swaps: ['today', 'tomorrow', 'this week'],
              distractors_es: ["I'll send to you the proposal today.", "I send you the proposal today."],
              cognateHook_es: '"proposal" es propuesta. Otra que te llegó regalada.',
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: 'c-ven-follow-up-friday',
              en: "I'll follow up on Friday.",
              es: 'Te escribo el viernes.',
              sounds_es: 'áil fólou ap on fráidei',
              why_es: '"follow up" es seguirle el rastro al asunto pa\' que no se enfríe. Decir el día exacto es lo que te salva: el cliente sabe cuándo esperar tu mensaje y tú ya no quedas de intenso cuando llegue.',
              sayWhen_es: 'Al cerrar la llamada, poniendo fecha al siguiente contacto.',
              who_es: 'con el cliente',
              frame: "I'll follow up on ___.",
              swaps: ['Friday', 'Monday', 'Tuesday'],
              distractors_es: ["I'll follow up in Friday.", "I'll follow on Friday up."],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
            {
              id: 'c-ven-thanks-for-your-time',
              en: 'Thanks for your time today.',
              es: 'Gracias por tu tiempo hoy.',
              sounds_es: 'zanks for iór táim tudéi',
              why_es: 'El cierre elegante, compre o no compre. Le agradeces el TIEMPO, que es lo único que seguro te dio. Con esa frase la puerta queda abierta pa\' volver en tres meses sin pena.',
              sayWhen_es: 'Al despedirte de una llamada de venta.',
              who_es: 'con el cliente',
              frame: null,
              swaps: null,
              distractors_es: ['Thanks for your time of today.', 'Thanks by your time today.'],
              cognateHook_es: null,
              forms: null,
              audio: null,
              survival: false,
            },
          ],
        },
      ],
      task: {
        id: 'job-ventas-u1-task',
        intro_es: 'Listo, se abre el Zoom y del otro lado hay un cliente gringo. Tranquilo, tú ya sabes vender…',
        steps: [
          {
            goal_es: 'Arranca la llamada. Abre mostrando qué hacen ustedes.',
            answerChunkId: 'c-ven-let-me-show-you',
            reaction_es: '¡Eso! Entraste sin pedir permiso dos veces.',
          },
          {
            goal_es: 'Te preguntan cuánto vale. Di el precio del plan mensual.',
            answerChunkId: 'c-ven-price-per-month',
            reaction_es: 'Derechito y sin temblar. Así se dice la plata.',
          },
          {
            goal_es: 'Se acaba la llamada y quedó interesado. Amarra el próximo contacto.',
            answerChunkId: 'c-ven-follow-up-friday',
            reaction_es: 'Perfecto. Con fecha puesta, esa venta no se enfría.',
          },
        ],
        done_es: 'Ya sabes SOSTENER UNA LLAMADA DE VENTA EN INGLÉS. ✓',
      },
    },
  ],
};
